### ISSUE TITLE
The "npm run cordova: xxx" commands do not seem to work.

### ISSUE THREAD

**Issue by treiero** [ngx-rocket/generator-ngx-rocket#117]
## I'm submitting a...

[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request

## Current behavior

I followed the documentation to create an App with Cordova and run the application on a device or simulator, but the command. Then I tried to build the application to package in an APK.

No "cordova" command as suggested in the documentation seems to work.
Ex:
npm run cordova: prepare
npm run cordova: run
npm run cordova: build

* Note: "npm start" works normally

## Expected behavior

I expected to create an App with "ngx new" and test it on my smatphone or simulator without having to create an App with separate Cordova and stay copying the contents of the dist or www folder to the Cordova project www folder.

## Minimal reproduction of the problem with instructions

_______________________________________
1- mkdir appTeste
_______________________________________
2- cd appTeste
_______________________________________
3- ngx new

? What's the name of your app? appTeste
? What kind of app do you want to create? Mobile app (using Cordova)
? Which mobile platform do you want to support? Android
? Use enhanced web view? [Android] Crosswalk
? Which UI framework do you want? Bootstrap (more website-oriented)
? Do you want authentication? no
_______________________________________
4- npm start

> app-teste@1.0.0 start D:\dev\appTeste
> ng serve --proxy-config proxy.conf.js

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
 10% building modules 3/3 modules 0 active[HPM] Proxy created: /api  ->  https://api.chucknorris.io
[HPM] Proxy rewrite rule created: "^/api" ~> ""
Date: 2017-08-24T13:33:08.724Z
Hash: 3cd88f292459ed79bf35
Time: 17483ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 86.9 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 328 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 242 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.89 MB [initial] [rendered]

webpack: Compiled successfully.

/*
 So far, so good and the app is generated normally, without errors.
*/
_______________________________________
5- npm run cordova:prepare

> app-teste@1.0.0 cordova:prepare D:\dev\appTeste
> ngx-scripts cordova prepare

/*
Apparently, nothing happens.
*/
_______________________________________
6- npm run cordova:run

> app-teste@1.0.0 cordova:run D:\dev\appTeste
> ngx-scripts cordova run

/*
Apparently, nothing happens. The app is not run on the simulator or device.
Device properly connected and tested using an app generated only with Cordova.
*/
_______________________________________
7- npm run cordova:build

> app-teste@1.0.0 cordova:build D:\dev\appTeste
> ngx-scripts cordova build --device --release --copy dist

Error during apps copy: No app builds found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-teste@1.0.0 cordova:build: `ngx-scripts cordova build --device --release --copy dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app-teste@1.0.0 cordova:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andre\AppData\Roaming\npm-cache\_logs\2017-08-24T13_43_10_787Z-debug.log

_______________________________________
8- cat /c/Users/andre/AppData/Roaming/npm-cache/_logs/2017-08-24T13_43_10_787Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\andre\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cordova:build' ]
2 info using npm@5.3.0
3 info using node@v6.9.1
4 verbose run-script [ 'precordova:build', 'cordova:build', 'postcordova:build' ]
5 info lifecycle app-teste@1.0.0~precordova:build: app-teste@1.0.0
6 info lifecycle app-teste@1.0.0~cordova:build: app-teste@1.0.0
7 verbose lifecycle app-teste@1.0.0~cordova:build: unsafe-perm in lifecycle true
8 verbose lifecycle app-teste@1.0.0~cordova:build: PATH: C:\Users\andre\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\dev\appTeste\node_modules\.bin;C:\Users\andre\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\andre\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\HashiCorp\Vagrant\bin;D:\gigro\ngrok;C:\Program Files\Sublime Text 3;D:\gigro\php-7.0.12-nts-Win32-VC14-x64;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs;C:\Users\andre\AppData\Roaming\npm\node_modules;C:\Program Files (x86)\PuTTY;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Bitvise SSH Client;C:\Python27;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Ruby23-x64\bin;C:\Users\andre\AppData\Local\Microsoft\WindowsApps;C:\Users\andre\AppData\Roaming\Composer\vendor\bin;C:\Users\andre\AppData\Roaming\npm;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle app-teste@1.0.0~cordova:build: CWD: D:\dev\appTeste
10 silly lifecycle app-teste@1.0.0~cordova:build: Args: [ '/d /s /c',
10 silly lifecycle   'ngx-scripts cordova build --device --release --copy dist' ]
11 silly lifecycle app-teste@1.0.0~cordova:build: Returned: code: 1  signal: null
12 info lifecycle app-teste@1.0.0~cordova:build: Failed to exec cordova:build script
13 verbose stack Error: app-teste@1.0.0 cordova:build: `ngx-scripts cordova build --device --release --copy dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid app-teste@1.0.0
15 verbose cwd D:\dev\appTeste
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andre\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "cordova:build"
18 verbose node v6.9.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error app-teste@1.0.0 cordova:build: `ngx-scripts cordova build --device --release --copy dist`
22 error Exit status 1
23 error Failed at the app-teste@1.0.0 cordova:build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Environment

```
- generator version: 1.2.2
- node version: 6.9.1
- npm version: 5.3.0
- OS:  Windows
```

Others:

**Comment by sinedied** [comment]
Thanks for the report, it's strange that `ngx-scripts` fails silently, I'll investigate this bug.

It bet it's a silly windows-related issue, as I develop on Mac and the CI is on Linux (the CI for Windows is WIP) 😉

**Comment by sinedied** [comment]
In fact, that was a silly issue: the commands needs to be spawned within a shell on Windows :/
The `@ngx-rocket/scripts` fix is released, but I'm still working on a generator update that forces the new version and that fixes another cordova-related issue.

**Comment by sinedied** [comment]
@treiero Does it work for you with the new `@ngx-rocket/scripts` version?

**Comment by treiero** [comment]
@sinedied Sorry for the delay of the response, I was in the hospital.

Now it works for me, however, as mentioned in your answer, there are still some dependency issues when running "cordova platform add android". I guess you meant exactly this problem in the previous message, so thank you for the quick resolution of the problem I posted.

Many thanks and congratulations for the work!

For the purpose of information only, the following is the output of the command "npm run cordova platform add android":


$ Npm run cordova platform add android

> Vicosa-atletico-clube@1.0.0 cordova D: \ dev \ ngxAtletico
> "Platform" "add" "android"

Using cordova-fetch for cordova-android@^6.2.3
Error: Failed to fetch platform cordova-android@^6.2.3
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name / version / URL.
Error: cmd: Command failed with exit code 1 Error output:
Npm WARN invalid config loglevel = "notice"
Npm ERR! Windows_NT 10.0.15063
Npm ERR! Argv "C: \\ Program Files \\ nodejs \\ node.exe" "D: \\ dev \\ ngxAtletico \\ node_modules \\ npm \\ bin \\ npm-cli.js" "install" "cordova-android @ 6.2.3 "" --save "
Npm ERR! Node v6.9.1
Npm ERR! Npm v2.15.12
Npm ERR! Code EPEERINVALID

Npm ERR! Peerinvalid The package postcss@5.2.17 does not satisfy its siblings' peerDependencies requirements!

Npm ERR! Please include the following file with any support request:
Npm ERR! D: \ dev \ ngxAtletico \ node_modules \ npm-debug.log
Npm ERR! Code ELIFECYCLE
Npm ERR! Errno 1
Npm ERR! Vicosa-atletico-clube@1.0.0 cordova: `cordova 'platform" "add" "android" `
Npm ERR! Exit status 1
Npm ERR!
Npm ERR! Failed at vicosa-atletico-clube@1.0.0 cordova script.
Npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Npm ERR! A complete log of this run can be found in:
Npm ERR! C: \ Users \ andre \ AppData \ Roaming \ npm-cache \ _logs \ 2017-08-30T13_12_29_157Z-debug.log

**Comment by sinedied** [comment]
Thanks for the feedback, I reproduce the same error on Windows and opened a separate issue for it: https://github.com/ngx-rocket/generator-ngx-rocket/issues/121

Seems that this time it's the `cordova-android` package that's broken (maybe due to `npm@5`?), I'll investigate this. The strange this is that it only  happens on Windows it seems...
