### ISSUE TITLE
Improve test examples

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#12]
- Add proper unit tests for components as examples
- Add simple e2e tests example (see https://github.com/angular-starter-kit/starter-kit)

**Comment by captaincaius** [comment]
As you noticed, I found myself taking shortcuts on ionic PR to get its e2e green.

I know you probably have broader goals for this, but if you don't mind, I'd like to propose a small PR to take a baby-step for this issue as far as e2e goes, and kill two birds with one stone (i.e. small progress here and unblocking the ionic4 PR w/o my hacks in that branch).

I'm waiting for all the tests to pass locally now, but here are the improvements I think it makes:

- better demonstrates separating actions from assertions (i.e. act by logging in, assert that you see welcome text)
- tests are independent, and nesting is demonstrated for preconditions (see https://github.com/angular/protractor/blob/master/docs/style-guide.md#make-your-tests-independent-from-each-other )
- demonstrates organization with multiple page-objects (see https://github.com/angular/protractor/blob/master/docs/style-guide.md#group-your-e2e-tests-in-a-structure-that-makes-sense-to-the-structure-of-your-project )
- page object instantiation pattern from style guide (see https://github.com/angular/protractor/blob/master/docs/style-guide.md#instantiate-all-page-objects-at-the-beginning-of-the-test-suite )

things that aren't quite perfect about the PR:

- the non-auth example of nesting is a bit contrived :P.  I think it still gets the idea across, but I don't know.
- it's treating "shell" as a page - users might get the idea, but I don't know.
- ...

further improvements we could make in the future (by no means an exhaustive list):

- clearing all state at the top-level for when more tests are added
- more tests?
- ...

lmk what you think

**Comment by captaincaius** [comment]
here's the branch diff while I wait...
https://github.com/captaincaius/generator-ngx-rocket/pull/1/files

**Comment by captaincaius** [comment]
PS... what I meant above by "contrived" was this...

auth output:

```
Jasmine started

  when the app loads
    ✓ should display the login page

    and the user logs in
      ✓ should display the hello message

Executed 2 of 2 specs SUCCESS in 5 secs.

```
non-auth output:

```
Jasmine started

  when the app loads
    ✓ should display the shell page

    and the page loads
      ✓ should display the hello message

Executed 2 of 2 specs SUCCESS in 5 secs.

```

**Comment by captaincaius** [comment]
Also...  Philosophical question here :P... I've never seen full consensus on best practice for this - do you think it's worthwhile to add test-specific attributes to the code, aside from what's already there? These are the various things I've seen people do:

- don't add anything to the code just for tests - use what's already there (like we're doing here)
- only select based on test-designated attributes added to the markup
- only select based on test-designated css classes added to the markup (yeah I know - that's not what they're for - but there are some arguments for it)

**Comment by bursauxa** [comment]
I personnally consider that adding stuff to the code just for tests is always bad design (whether it is bad design of the tests, or bad design of the code, depends on situations - and sometimes bad design is an acceptable trade-off versus other limitations).

However, this is philosophical as you said, and I know others who have differing opinions. I am not sure what stance we want to take for ngx-rocket.

**Comment by sinedied** [comment]
Closing as existing tests may be crude, but do the job anyways, adding more would depend on your project test policy in the end.
