### ISSUE TITLE
production build not working on IE 11

### ISSUE THREAD

**Issue by omkarbGithub** [ngx-rocket/generator-ngx-rocket#123]
## I'm submitting a...

[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

production build not working on IE11, it gives warning on screen to update browser version.

## Expected behavior

production build should work on IE 11

## Minimal reproduction of the problem with instructions

ng build -prod -aot

## Environment

```
- generator version: X.Y.Z
- node version: 6.10.0 <!-- run `node --version` -->
- npm version: 3.10.10  <!-- run `npm --version` -->
- OS:  Windows 10<!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment]
I cannot reproduce your issue, on the same environment. You should check out if emulation options are enabled in your IE11 settings, as the update screen is only displayed for browsers < IE10:
![image](https://user-images.githubusercontent.com/593151/30014815-92ebc58e-914e-11e7-8327-a8d58dfb697e.png)

**Comment by omkarbGithub** [comment]
@sinedied : thanks, but I checked emulation options, its exact similar to you.
But, see the screen shot bellow
![image](https://user-images.githubusercontent.com/31608976/30015168-3e8afff4-916d-11e7-87ab-f2a4213688bc.png)

**Comment by sinedied** [comment]
Did you change anything in `index.html`?
These are the lines responsible for this message:
```
  <!--[if lt IE 10]>
  <p>
    You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
  </p>
  <![endif]-->
```

Also, are you using a company-managed computed? I used to see some company's group policies affecting the default rendering mode of IE to force compatibility mode for their internal web apps, maybe that's something related?

What's the detected browser version with http://detectmybrowser.com ?

**Comment by omkarbGithub** [comment]
Yes, After build I have renamed the bundle file names, and also their path in index.html file. Will that caused this warning message?

And about my browser it shows "You're using Mozilla version 11 on Windows".

**Comment by sinedied** [comment]
Do you reproduce the issue with a brand new project?
```
ngx new
npm run env && npm run start -- --prod
```

It seems that your browser is fine, and just renaming the bundles should not have caused this. What's the web server that is hosting your app?

**Comment by sinedied** [comment]
@omkarbGithub Any news? Did you reproduce with a fresh project?

**Comment by sinedied** [comment]
I'm closing this due to the lack of feedback, feel free to comment if you still have issues.
