### ISSUE TITLE
AOT support?

### ISSUE THREAD

**Issue by msarsha** [ngx-rocket/generator-ngx-rocket#131]
## I'm submitting a...

[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request

## Current behavior
No reference in the readme about AOT

## Expected behavior
Should support angular's AOT

**Comment by bursauxa** [comment]
If you run the npm `build` script, it calls `ng build --prod`, which enables AOT.

For reference:
https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds
