### ISSUE TITLE
HMR (Hot Module Replacement) support?

### ISSUE THREAD

**Issue by eladcandroid** [ngx-rocket/generator-ngx-rocket#132]
## I'm submitting a...

[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request

https://github.com/AngularClass/angular-hmr

Article that explains how to implement it on Angular-CLI:
https://medium.com/@beeman/tutorial-enable-hmr-in-angular-cli-apps-1b0d13b80130

**Comment by sinedied** [comment]
That would be a nice addition, I assumed that the `--hmr` option to `angular-cli` would do the trick but reading the article you pointed it seems there's a bit of extra work to make use of it.

That could be a generator question, whether the `npm start` script should use HMR or it.
