### ISSUE TITLE
Analytics addon

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#136]
It would be nice to have an addon that adds basic analytics support (ie page tracking) out of the box.
I thought of using [Angulartics2](https://github.com/angulartics/angulartics2) as it's vendor agnostic and flexible, but other suggestions may be welcome.

- [x] create addon with name: `addon-analytics`
- [x] add generator questions:
  * `Do you want to add analytics to your app?` -> Y/n
  * `Which analytics provider do you want to use?` -> list, support at least Google Analytics and Piwik
- [x] add documentation: `docs/analytics.md` with how-to usage to add event tracking or change provider
- [x] add code integration for the supported providers

**Comment by bursauxa** [comment]
Since HTML injection is not possible in the current state of addons, and since we want to have in-HTML examples of event tracking, the analytics module will be an integral part of the generator and not an addon.

**Comment by bursauxa** [comment]
Generator questions, templating, and examples are done for Google Analytics.

For other providers, only the npm package and module import are effectively done. Angulartics themselves only provide full examples for Google Analytics and Google Tag Manager, so I am not sure that we should go any further in implementations.

Documentation is coming :soon:.

**Comment by bursauxa** [comment]
I fixed unit tests (on my machine at least, CI build are in the pipe) and added some documentation, with adaptations between Google Analytics and the rest. This issue should be resolved once !294 is pulled.
