### ISSUE TITLE
Error building Cordova App

### ISSUE THREAD

**Issue by johoehn** [ngx-rocket/generator-ngx-rocket#137]
## I'm submitting a...
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
Each time I run "npm run cordova:build" I get an error message as below: 

_Error: /Users/user/Desktop/test/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeReleaseResources'.
> /Users/user/Desktop/test/platforms/android/res/extra/README.md:1:1: Error: Content ist nicht zulässig in Prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output._

## Minimal reproduction of the problem with instructions
1. install ngx new
2. select Responsive web app and Mobile app, iOS and Android, deselect WKWebView and Crosswalk, select Bootstrap, select no authentication

## Environment
newest node and npm versions, latest mac osx

**Comment by sinedied** [comment]
I'm investigating the issue, which version of the `android-build-tools` do you use?

In the meantime your can delete the `resources/android/extra/README.md` file as it is just a placeholder, to see if it fixes your issue.

**Comment by johoehn** [comment]
I am running an android-build-tools version 25.0.2. 
Removing the README.md file solved the problem. Thanks for your fast help!

**Comment by sinedied** [comment]
Found the issue, the support scripts were copying the files in the wrong place.
You can prevent future issues by running `npm install -D @ngx-rocket/scripts@latest` in your project.
