### ISSUE TITLE
Route not created - generate component

### ISSUE THREAD

**Issue by HaakonH** [ngx-rocket/generator-ngx-rocket#142]
## I'm submitting a...

[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request

## Current behavior

When I run:
npm run generate -- component myComponentName

The generator runs and creates my new component but a route isn't autogenerated?

## Expected behavior

Similar to the original yo angular generator it would create a route, someComponentName-routing.module.ts and add those file links to any files necessary to enable that route after it builds.

## Minimal reproduction of the problem with instructions

1. Open a command window in a folder where you have successfully built and run a ngx-rocket generator.
2. Run the command "**npm run generate -- component someComponentName**"
3. Run "**npm run build**"
4. Run "**npm start**"
5. Navigate to "**http://localhost:4200/home**" - If page loads then build was successful.
6. Try to open "**http://localhost:4200/someComponentName**" << This won't work and you will be redirected back to the default home page.

## Environment
- generator version: 1.0.3
- node version: v6.9.1
- npm version: 3.10.8 
- OS: Windows

Others:

**Comment by sinedied** [comment]
The `generate` script is just an alias to the `ng generate` command, so you should post an issue on the [angular-cli repo](https://github.com/angular/angular-cli) for this one.

But what you're trying to achieve is not something desired for all components: a component is not a direct equivalent of AngularJS's view/controller, as there can be dumb components (only used for presentation) and smart components with the data logic (that might encapsule other smart and dumb components).
On the other hand, as it is specified on the [Angular Style Guide](https://angular.io/guide/styleguide#angular-ngmodule-names) you should create a new module with eventually a routing module to put your components into:
```
ngx generate module yourModule --routing // generate a new module with a new routing module
ngx generate component yourComponent --module yourModule // adds a new component to the module
```
But this won't generate the route automatically for your (you can still propose the option to angular-cli team) as for dumb components it does not make sense.

**Comment by HaakonH** [comment]
This makes sense, I'm still getting used to the new format so forgive my ignorance on this subject. I tried your suggestion and it worked perfectly! I really appreciate your guidance with this request.
