### ISSUE TITLE
Integration with Meteor Backend and Meteor Client

### ISSUE THREAD

**Issue by jayserdny** [ngx-rocket/generator-ngx-rocket#156]
Could be great if the cli could have predefined configuration for backends such as Meteorjs, Firebase, etc... I will try to integrate meteorjs with this and see if it works (because in Ionic cli it is not working).

**Comment by sinedied** [comment]
Definitely, this is on the roadmap actually, see https://github.com/ngx-rocket/addon-firebase which is the very first step towards Firebase integration (auth and more is planned for later).

You could create a similar addon for MeteorJS if you want to give a try.
We would prefer to keep these as separate addons so they can be maintained separately from the main generator code base.

**Comment by jayserdny** [comment]
The problem is that to implement meteorjs I need to eject webpack. Ejecting webpack will remove most of the funcionality

**Comment by sinedied** [comment]
That could work if you include the ejected webpack config as part of your addon template, but that means extra work will be needed to keep up with angular CLI updates :/

I'm not familiar with MeteorJS, but seeing [this example repo](https://github.com/darkbasic/angularcli-meteor), from what I see in webpack config's patches, I think it could be done using only the `tsconfig.json` file.

**Comment by jayserdny** [comment]
To be honest, I tried it without webpack. Then, I messed up everything by adding webpack hahhah. I mean, it was connected to localhost port by DDP. I will try again and if so, is there a pattern used to create add-ons to this project? I would like to contribute this. Working Meteor with ionic cli is a headache because it always gives errors.

**Comment by sinedied** [comment]
> is there a pattern used to create add-ons to this project? 

You can use the CLI with the command `ngx new --addon` to get started.
Addons are standard [Yeoman](http://yeoman.io/authoring/index.html) so their docs can be used, but helpers are provided with [@ngx-rocket/core](https://github.com/ngx-rocket/core) to get started more easily.

**Comment by jayserdny** [comment]
I was looking at it. Sadly, Meteor requires to eject Webpack in order to allow Angular to communicate with Meteor dependencies. For example, if I implement Meteor in an Angular app, I will be able to connect through DDP. However, I will have not access to minimongo collection from client side forcing me to use pubs/subs/methods for any single data.

**Comment by sinedied** [comment]
Closing as it seems to be dropped.
