### ISSUE TITLE
Add mobile app builds to CI

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#162]
Currently the CI generates apps for various cases and build, runs unit and e2e tests those apps on both Linux and Windows.

What's still missing is buildings app for iOS/Android for the hybrid uses cases (or at least one case, like mobile/ionic/auth).

Travis supports OSX images, but I'm not sure whether complete testing for web and android would work using this, as only 1 base image can be used for a repo.

Another CI provider could be used like [CircleCI](https://circleci.com/) or anything that could fit the job.

**Comment by sinedied** [comment]
The idea is to at least build apps for Android (already done via CircleCI) and iOS, and if we can publish the artifacts (APK/IPA) somewhere (I had Hockeyapp in mind) so we can do a quick sanity check before a release.
Phonegap could be a possibility, I don't know it well and I was more in favor of traditional CI for more control (I think?), but all suggestions are good :)

**Comment by captaincaius** [comment]
Cool!  Looks like you're already progressing on it :).

Looking forward to learning from the setup :).

**Comment by captaincaius** [comment]
by the way, quick note in case you're interested - getting any CI to push a phonegap-build build is a one-liner:
curl -X PUT -F file=@./clientapp/rocket/dist/app-phonegap.zip https://build.phonegap.com/api/v1/apps/yourappid?auth_token=${PHONEGAP_AUTHTOKEN}

No need to even touch cordova on CI before sending it to them - the zipfile is just config.xml www/ resources/

I know you're testing on windows too so it's not that simple, but just so you know ;).

**Comment by sinedied** [comment]
Forgot to close that one, its already implemented 🙂
