### ISSUE TITLE
Translation dropdown doesn't do anything

### ISSUE THREAD

**Issue by bostondevin** [ngx-rocket/generator-ngx-rocket#165]
In the sample app, switching the translation dropdown between french and english doesn't do anything - I would expect all the labels to change to the specified language.

## I'm submitting a...

[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

In the sample app, switching the translation dropdown between french and english doesn't do anything

## Expected behavior

The labels should change language

## Minimal reproduction of the problem with instructions

Change language dropdown

## Environment

```
- generator version: latest (2.3.0)
- node version: 8.9.0  <!-- run `node --version` -->
- npm version: 5.5.1  <!-- run `npm --version` -->
- OS: Mac, Windows <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment]
Which OS, generator, node and npm versions? Did you change anything in the template?

**Comment by bostondevin** [comment]
Sure - filled those in. It was all the latest versions on a Mac, but I also saw the same behavior on my Windows as well

**Comment by vpzed** [comment]
I can confirm.  I just did a fresh install on Linux and it is doing the same.  Nothing was changed after doing "ngx new".  

In the generator:

     What kind of app do you want to create? Web app
     Do you want a progressive web app? (with manifest and service worker) Yes
     Which UI framework do you want? Angular Material (more website-oriented)
     Do you want authentication? No

Something isn't working with the i18n stuff because it is also showing APP_NAME on the site.

I also included a screenshot and all information below.

	 ~/dev/ngx-rocket/angular $ npm list --depth=0
	someapp@1.0.0 /home/devuser/dev/ngx-rocket/angular
	+-- @angular/animations@4.4.6
	+-- @angular/cdk@2.0.0-beta.12
	+-- @angular/cli@1.5.0
	+-- @angular/common@4.4.6
	+-- @angular/compiler@4.4.6
	+-- @angular/compiler-cli@4.4.6
	+-- @angular/core@4.4.6
	+-- @angular/flex-layout@2.0.0-beta.9
	+-- @angular/forms@4.4.6
	+-- @angular/http@4.4.6
	+-- @angular/language-service@4.4.6
	+-- @angular/material@2.0.0-beta.12
	+-- @angular/platform-browser@4.4.6
	+-- @angular/platform-browser-dynamic@4.4.6
	+-- @angular/router@4.4.6
	+-- @angular/service-worker@1.0.0-beta.16
	+-- @biesbjerg/ngx-translate-extract@2.3.2
	+-- @ngx-rocket/scripts@1.0.5
	+-- @ngx-translate/core@8.0.0
	+-- @types/jasmine@2.6.2
	+-- @types/jasminewd2@2.0.3
	+-- @types/lodash@4.14.80
	+-- @types/node@8.0.47
	+-- codelyzer@3.2.2
	+-- core-js@2.5.1
	+-- hads@1.4.1
	+-- hammerjs@2.0.8
	+-- htmlhint@0.9.13
	+-- https-proxy-agent@2.1.0
	+-- jasmine-core@2.8.0
	+-- jasmine-spec-reporter@4.2.1
	+-- karma@1.7.1
	+-- karma-chrome-launcher@2.2.0
	+-- karma-cli@1.0.1
	+-- karma-coverage-istanbul-reporter@1.3.0
	+-- karma-jasmine@1.1.0
	+-- karma-junit-reporter@1.2.0
	+-- lodash@4.17.4
	+-- material-design-icons@3.0.1
	+-- protractor@5.1.2
	+-- puppeteer@0.11.0
	+-- rxjs@5.5.2
	+-- stylelint@8.1.1
	+-- stylelint-config-recommended-scss@2.0.0
	+-- stylelint-config-standard@17.0.0
	+-- stylelint-scss@2.1.0
	+-- ts-node@3.3.0
	+-- tslint@5.7.0
	+-- typescript@2.4.2
	+-- zone.js@0.8.18

	 ~/dev/ngx-rocket/angular $ node --version
	v8.9.0
	 ~/dev/ngx-rocket/angular $ npm --version
	5.5.1
	 ~/dev/ngx-rocket/angular $ uname -a
	Linux devbox 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

![example](https://user-images.githubusercontent.com/30138020/32401665-994c9e54-c0e1-11e7-8779-4be782a5e80f.png)

**Comment by sinedied** [comment]
Thanks for the report! It may be related to either the new version of ngx-translate or angular-cli, I will take a look.

**Comment by sinedied** [comment]
This is fixed in the latest `2.3.1` version, json files were not imported correctly with latest `angular-cli@1.5`.

If you are using `@ngx-rocket/cli`, you need to do this to make sure you get the updated version:
```sh
npm rm -g @ngx-rocket/cli
npm cache clean
npm i -g @ngx-rocket/cli
```

**Comment by vpzed** [comment]
Awesome!  I'll give it a try later this week.  Thank you for the great project.  I look forward to growing with it into Angular 5.

**Comment by bostondevin** [comment]
It works! Thanks! You Rocket my world!
