### ISSUE TITLE
Best way to upgrade/update templated project

### ISSUE THREAD

**Issue by SpiraMira** [ngx-rocket/generator-ngx-rocket#175]
## I'm submitting a...

[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request

## Current behavior

Question for anyone:

I generated (ngx new) an ng 4.x based project a week ago.
There are ng 5.x changes checked in already, so a new release of the template is imminent
Besides manually merging/cherry picking the changes, does this toolchain support updates/upgrades?
If so, how?
If not, what is the most efficient method?

I have manually updated my project to 5.x using Angular docs. Just wondering about stuff in core, themes and other shared ngx-rocket services.

Thanks in advance.
## Expected behavior

N/A

## Minimal reproduction of the problem with instructions

N/A

## Environment

```
- generator version: X.Y.Z
- node version: X.Y.Z  <!-- run `node --version` -->
- npm version: X.Y.Z  <!-- run `npm --version` -->
- OS:  <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment]
Good grief, it's effectively missing from the docs!
When we will release the new generator version with Angular@5 support, this will be the basic update workflow:
- make sure your working directory is clean (no pending / uncommited changes)
- run `ngx update` (using the [CLI](https://github.com/ngx-rocket/cli))
- the generator will then run again using the same options you used, and you can either:
  * see the diff for each changed files and choose to overwrite or not
  * or better, overwrite everything then use your source control to see the diff and merge the changes

This is not perfect for now as html/components are also overwritten, but #144 will help for that in the future. With a good git UI (webstorm, vscode...) merging the new changes can be done in a few minutes though.

I'll keep this issue open until a proper update guide is written, this would definitely be useful 😄

**Comment by SpiraMira** [comment]
Excellent! I know this is a (great) work in progress and we can't have all of our cake and eat it too :D
But thanks for keeping this on the radar.

By the way - my initial foray into rocket+Angular 5 is promising. I know there are (blocking?) issues with the Http client etc. so I am using a home grown authentication service for now. Otherwise the port doesn't seem too problematic - the gain in features and performance is well worth it (imho)

Regards.
