### ISSUE TITLE
Implement lazy loading 

### ISSUE THREAD

**Issue by nileshpatilwork** [ngx-rocket/generator-ngx-rocket#195]
Thanks for this great tool!
I am not able to implement lazy loading using route shell 
I have tried to add loadchildren in about route about-routing.module.ts like below
const routes: Routes = Route.withShell([
    {
        path: 'about',
        component: AboutComponent,
        data: { title: 'About' },
        loadChildren: './about.module#AboutModule',
    }
]);
when I hit ng serve I am getting below warning
**WARNING in Duplicated path in loadChildren detected during a rebuild. We will take the latest version detected and override it to save rebuild time. You should perform a full build to validate that your routes don't overlap.**

and I am unable to click on about route as i am getting below error in developer console

**core.js:1350 ERROR Error: Uncaught (in promise): Error: Component ShellComponent is not part of any NgModule or the module has not been imported into your module.
Error: Component ShellComponent is not part of any NgModule or the module has not been imported into your module.**

but when I build the app using ng build --prod and access the application using node express 
its working file and also lazy loading working fine for the about module

I dont know whether this issue or not  but as I am going to develop enterprise level application I want to use router lazy loading feature 

ngx version 
1.6.0

**Comment by sinedied** [comment]
This won't work like this, see https://angular-2-training-book.rangle.io/handout/modules/lazy-loading-module.html for an in-depth explanation of how lazy loading works, but in short:

- You have to remove `AboutModule` from the `app.module.ts` imports
- The routes definition that tells which module to lazy needs to be in your root route definition, ie in `app-routes.module.ts`: `{ path: 'about', loadChildren: 'app/about/about.module#AboutModule' }`

  The complete route definition would look like:
  ```ts
  const routes: Routes =[
    {
      path: '',
      component: ShellComponent,
      children: [
        { path: 'about', loadChildren: 'app/about/about.module#AboutModule' },
      ],
      canActivate: [AuthenticationGuard],
      // Reuse ShellComponent instance when navigating between child views
      data: { reuse: true }
    },
    // Fallback when no prior route is matched
    { path: '**', redirectTo: '', pathMatch: 'full' }
  ];
  ```
- The route definition in `about-routing.module.ts` should be adapted to match only when it's lazy loaded: 
  ```ts
  const routes: Routes = [
    { path: '', component: AboutComponent, data: { title: extract('About') } }
  ];
  ```

I'll try to put up an example repo quickly, maybe even make it a generator option if I have time for it :wink:

**Comment by sinedied** [comment]
I figured out how to make it work with `Route.withShell()` in `app-routing.module.ts`:
```ts
const routes: Routes = Route.withShell([
  { path: 'about', loadChildren: 'app/about/about.module#AboutModule' }
]);
routes.push({ path: '**', redirectTo: '', pathMatch: 'full' });
```
So it's even simpler 😉 

(Originally I was using `concat` to merge the routes but that breaks the Angular compiler)

**Comment by nileshpatilwork** [comment]
I already tried second approach but with this I am unable to click on about route in development. 
Please give a try

**Comment by sinedied** [comment]
You may have missed something, take a look here for an example implementation: https://github.com/sinedied/ngx-rocket-lab
No issue when navigating to and from about screen 😉 

As for suggestions, you are welcome to open an issue on github to propose your ideas. 
Concerning HttpClient/Interceptor, see https://github.com/ngx-rocket/generator-ngx-rocket/issues/94 and for form validation/async example you can take a look at the login page and https://github.com/ngx-rocket/generator-ngx-rocket/issues/186.

**Comment by sinedied** [comment]
@nileshpatilwork Did you succeed based on the example?

**Comment by nileshpatilwork** [comment]
No. Same problem unable to click on about link

On Dec 11, 2017 1:46 PM, "Yohan Lasorsa" <notifications@github.com> wrote:

@nileshpatilwork <https://github.com/nileshpatilwork> Did you succeed based
on the example?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ngx-rocket/generator-ngx-rocket/issues/195#issuecomment-350651522>,
or mute the thread

**Comment by sinedied** [comment]
Do you have the same issue with the example repo I provided you, when running with `npm start`?

**Comment by nileshpatilwork** [comment]
Hi, I have used your repo and its working fine now. Thanks.
Can we have httpClient instead http?
This plugin is to generate enterprise level projects then why you are included http cache service?
please implement lazy loading in upcoming updates :)

**Comment by sinedied** [comment]
Good to hear that it's working now :)

As for HttpClient, see https://github.com/ngx-rocket/generator-ngx-rocket/issues/94
Http cache is enabled as most of the time you want some caching/persistence strategy in enterprise apps.

And I keep this issue open to integrate a lazy loading choice in a next release.

**Comment by nileshpatilwork** [comment]
Awesome to see progress on this :+1:
