### ISSUE TITLE
Can't implement routing correctly with a new component

### ISSUE THREAD

**Issue by southapps** [ngx-rocket/generator-ngx-rocket#206]
Hi! I'm new at Angular 5 routing, and I'm trying to implement navigation to a new component I've created (using npm run generate -- component <ComponentName> skip-import).

This is my code for the routing module:

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { Route } from '../core/route.service';
import { extract } from '../core/i18n.service';
import { OfferDetailComponent } from './offer-detail.component';

const routes: Routes = Route.withShell([
  { path: 'item/:offerId', component: OfferDetailComponent }
]);

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: []
})
export class OfferDetailRoutingModule { }

```

My component module:

```
@NgModule({
  imports: [
    CommonModule,
    TranslateModule,
    CoreModule,
    SharedModule,
    FlexLayoutModule,
    MaterialModule,
    OfferDetailRoutingModule
  ],
  declarations: [
    OfferDetailComponent
  ]
})
export class OfferDetailModule { }

```
Also, i've referenced the component's module in "app.module.ts".

However, when I try to navigate the module, nothing happens. The navigation event occurs on the stock HomeComponent with a "routerLink="/item/40" attribute.

Any idea what i might be doing wrong?

Thanks in advance!

**Comment by southapps** [comment]
So, I found the issue:

The problem was that AppRoutingModule was imported before my ComponentModule. AppRoutingModule has to be imported last:

```
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    TranslateModule.forRoot(),
    BrowserAnimationsModule,
    MaterialModule,
    CoreModule,
    SharedModule,
    HomeModule,
    AboutModule,
    LoginModule,
    OfferModule,
    AppRoutingModule
  ],
```

**Comment by sinedied** [comment]
Thanks for sharing the solution to others.
Indeed, the module import order is important, and the `AppRoutingModule` should also always be last as it is one declaring the fallback.
