### ISSUE TITLE
Heroku deployment fails :(

### ISSUE THREAD

**Issue by HaakonH** [ngx-rocket/generator-ngx-rocket#209]
## I'm submitting a...

[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request

## Current behavior

Upon deployment of app to heroku fails. 

## Expected behavior

Some sort of documentation about how to deploy to heroku.

## Minimal reproduction of the problem with instructions

1. Run ngx new and create a test app.
2. Go to heroku and create a new application and click on the deploy tab. 
3. Login to heroku in your cmd window and then in the folder where you created your test app run the heroku git command to make it a heroku git app.
4. Run the git add . then do a git commit -m 'initial commit'
5. Then run - git push heroku master
6. The app will build and push to heroku. A link will be generated in the script. If you click the link you will  get an error. 
7. Looking in the logs on heroku or by running - heroku logs - in your command window will display:
 Failed at the test@1.0.0 start script.

## Environment

```
- generator version: 3.1.1
- node version: 8.9.3  <!-- run `node --version` -->
- npm version: 5.5.1  <!-- run `npm --version` -->
- OS: Windows 7 Enterprise  <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment]
Please take a look at https://medium.com/@hellotunmbi/how-to-deploy-angular-application-to-heroku-1d56e09c5147, it's not that simple: Heroku is not able to host a webapp directly, you need to provide a server.

You may take a look at Firebase and https://github.com/ngx-rocket/addon-firebase if you want a free hosting solution supporting webapp deployment directly.

While an Heroku deployment addon may be coming someday like the one for Firebase, it's outside the scope of the generator and it's already well documented on Medium, Stackoverflow and others.
