### ISSUE TITLE
 NG Live Development Server LocalIP

### ISSUE THREAD

**Issue by Jamie-Vangeysel** [ngx-rocket/generator-ngx-rocket#210]
## I'm submitting a...
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request

## Current behavior
Can't access the Development server it's running on http://localhost:4200/ 

## Expected behavior
Default to listening on both http://localhost:4200/ and http://<localIP>:4200/

## Environment
- OS:  
```

Others:
Before I finally decided to go to Angular 4 I was using Angular 1 with Browsersync, that defaulted to using port 3000 on localhost and local ip, in this environment I am not able to run it just locally.
We have a dev server where all the projects are stored etc, We don't have admin rights on our pc's and we have no node.js etc installed everything has to go via the server, the only tools I have are putty and visual code. Since I cannot acces http://localhost:4200/ from my pc It would be quite difficult to test ;P
I there a way to change this port since I din't really find it in any config file.

**Comment by dvaJi** [comment]
You can change the default port just adding `--port DEFAULTPORT` in your ng serve script
example package.json:
`"start": "ng serve --aot --proxy-config proxy.conf.js --port 3000",`

**Comment by Jamie-Vangeysel** [comment]
Thanks

**Comment by Jamie-Vangeysel** [comment]
For desired behaviour:
`ng serve --aot --proxy-config proxy.conf.js --host 0.0.0.0 --port 3000`
