### ISSUE TITLE
No menu inside Cordova

### ISSUE THREAD

**Issue by aSegatto** [ngx-rocket/generator-ngx-rocket#215]
## I'm submitting a...

[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
When I generate a mobile app with this settings : 

`{
  "generator-ngx-rocket": {
    "version": "3.1.1",
    "props": {
      "appName": "lol",
      "target": [
        "cordova"
      ],
      "mobile": [
        "android"
      ],
      "ui": "material",
      "layout": "simple",
      "auth": false,
      "projectName": "lol",
      "packageManager": "npm"
    }
  }
}`

then inside cordova app I can't see the menu. Its present but it has no style . Inside Chrome works correctly , also with mobile emulation 
![screenshot from 2018-01-11 15-25-03](https://user-images.githubusercontent.com/2684687/34830252-a4779db4-f6e3-11e7-83aa-a6e4e433bd6d.png)

## Environment
"version": "3.1.1"

**Comment by sinedied** [comment]
Did you try on a real device?
The Android emulator have often rendering issues with embedded web views.

**Comment by aSegatto** [comment]
yes it's working on my smartphone, no chance to make it work on the emulator ? on my pc with ionic-angular works fine , but with material doesn't ...

**Comment by sinedied** [comment]
I can't really do a thing about this, it's most likely due to hardware accelerated textures inside the browser which are badly supported in the emulator.

You could try disabling the GPU acceleration in your Android Virtual Device settings, that may work better, though slower.

**Comment by aSegatto** [comment]
I'll try ! Thanks for your support !! :blush:

**Comment by sinedied** [comment]
Just for the record, the same issue occurs on iOS simulator, so it seems angular-material really have some CSS that the emulators don't like 😄

**Comment by sinedied** [comment]
I'm reopening this as the issue could be reproduced also on desktop Safari, I have reported this on the angular-material repo: https://github.com/angular/material2/issues/9403

**Comment by aSegatto** [comment]
I'll follow the issue ! Thanks for the effort 😄
