### ISSUE TITLE
How to add Cordova Plugin

### ISSUE THREAD

**Issue by nandi-krisanu** [ngx-rocket/generator-ngx-rocket#216]
Hi,
I want to know how to add Ionic Native Cordova Plugin. 
The installation procedure as per Ionic Native Docs says:
```
1. npm install @ionic-native/core --save
2. ionic cordova plugin add cordova-plugin-tts
3. npm install --save @ionic-native/text-to-speech
4. Then import the plugin module
i.e  import { TextToSpeech } from '@ionic-native/text-to-speech';
```

If I run 
`"ionic cordova plugin add cordova-plugin-tts"`
command , It says it is not Cordova based project.

**Comment by sinedied** [comment]
This is the procedure if you use the ionic platform (CLI), which is not the case here.
Though, the procedure is not much different, we just use cordova directly through npm script:
```
2. ngx cordova plugin add cordova-plugin-tts // or npm run cordova -- plugin add cordova-plugin-tts
```

**Comment by subhendusett** [comment]
Hi,
I faced the same problem I used 'ngx cordova plugin add cordova-plugin-tts' and successfully installed 'cordova-plugin-tts' but when I try to run 'npm install --save @ionic-native/text-to-speech' 
I found this error. 

```
npm WARN postcss-html@0.11.0 requires a peer of postcss-sass@>=0.2.0 but none is installed. You must install peer dependencies yourself.
npm ERR! path E:\Workspace\Angular\waymaker\WayMaker\node_modules\cordova-lib\node_modules\npm\node_modules\dezalgo\node_modules\asap
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'E:\Workspace\Angular\waymaker\WayMaker\node_modules\cordova-lib\node_modules\npm\node_modules\dezalgo\node_modules\asap' -> 'E:\Workspace\Angular\waymaker\WayMaker\node_modules\cordova-lib\node_modules\npm\node_modules\dezalgo\node_modules\.asap.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\weaversAndroid\AppData\Roaming\npm-cache\_logs\2018-01-15T07_10_07_524Z-debug.log
```


Please help me regarding this issue

**Comment by sinedied** [comment]
@subhendusett This is a know NPM problem: https://github.com/npm/npm/issues/19569
It happens sometimes on `npm install` commands.
Try deleting your `node_modules` folder and performing `npm install` again.

**Comment by nandi-krisanu** [comment]
Thank you for reply, all works.
