### ISSUE TITLE
Can't scroll on iOS

### ISSUE THREAD

**Issue by 2peter3** [ngx-rocket/generator-ngx-rocket#217]
## I'm submitting a...
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
Can't scroll on iOS

## Expected behavior
Scrolling :)

## Minimal reproduction of the problem with instructions
Installing a fresh version with this Settings:
```
? What's the name of your app? bb
? What kind of app do you want to create? Web app, Mobile app (using Cordova)
? Do you want a progressive web app? (with manifest and service worker) Yes
? Which mobile platform do you want to support? iOS
? Which UI framework do you want? Bootstrap (more website-oriented)
? Do you want authentication? Yes
```

After this prepare cordova with:
`npm run cordova:prepare`

Now add some long text to src/app/home/home.component.html

example:
```
...
        </h1>
        <br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br
        />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />t<br />kkkkkkkkkk
        <app-loader [isLoading]="isLoading"></app-loader>
....
```

and build cordova with
`npm run cordova:build`

Go to XCode, Open Project and Select the Developer Team and Run it on Device.

Scrolling wont work, so nobody wont see "kkkkkkkkkk"

## Environment

```
- generator version: v3.1.1
- node version: v9.3.0
- npm version: 5.6.0
- OS:  Mac
```

Others:
-

**Comment by sinedied** [comment]
I can reproduce the issue on the simulator. Did you also try it on a real device? (I don't have one at hand)

**Comment by 2peter3** [comment]
Yes, i have tested it on real device iPhone 6s and Simulator :/

**Comment by 2peter3** [comment]
you have any ideas/hints what could be the problem?

**Comment by sinedied** [comment]
I'm currently trying to isolate the issue, I think it's something in Bootstrap that's causing the issue as the problem do not exist when using Ionic or Angular Material.
I am trying the latest Bootstrap beta branch to see if it fixes the issue, I'll keep you updated if I find something.

**Comment by sinedied** [comment]
Same behavior with latest Bootstrap beta, it seems that there's an element capturing the scrolling event, still investigating...

**Comment by sinedied** [comment]
Removing `cordova-plugin-ionic-webview` with `ngx cordova plugin rm cordova-plugin-ionic-webview` fixes the issues, but changes the webview to the slower UIWebView instead of WKWebView.

I will try with the official cordova WKWebView plugin to see if it works or not.

**Comment by 2peter3** [comment]
i think i have found a solution... add to config.xml

`
<preference name="ScrollEnabled" value="true" />
`

between "<platform name="ios">" and </platform>

@sinedied could you approve it?

**Comment by sinedied** [comment]
I cannot test it at the moment, but it seems a viable fix, seeing https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/master/src/ios/CDVWKWebViewEngine.m#L377

I could not find a documentation for this setting anywhere though, so I'm unsure of the reason for the default value being false. What's even more strange is that in previous `cordova-plugin-ionic-webview` version scrolling was working fine even without this settings 😕 

Thanks for finding this fix, I'll add it specifically for the mobile/Bootstrap generation path since it's not needed when using Ionic or Angular Material 👍

**Comment by sinedied** [comment]
@2peter3 I just tested the workaround, the scrolling works as expected.
You may also want to change `<preference name="UIWebViewBounce" value="false" />` with the `true` value to restore native webview bounce when scrolling.
