### ISSUE TITLE
New Android Mobile App Error when install jquery

### ISSUE THREAD

**Issue by compleatguru** [ngx-rocket/generator-ngx-rocket#219]
## I'm submitting a...

[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
ngx new
with Andriod option
with IonicFramework option
then npm i --save jquery
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename './node_modules/cordova-lib/node_modules/npm/node_modules/ansistyles' -> './node_modules/cordova-lib/node_modules/npm/node_modules/.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.

## Expected behavior
jquery installed

## Environment

```
- generator version: 3.1.1
- node version: 9.3.0
- npm version: 5.6.0
- OS: Ubuntu
```

Others:

**Comment by sinedied** [comment]
This is a known issue with npm@5: https://github.com/npm/npm/issues/19569, sometimes `npm install` commands fails for no reason.
Best solution is to `rm -rf node_modules` folder and try `npm install` again 😕 

You can also try https://yarnpkg.com as an alternative to npm, which is not affected by this issue.

Unfortunately, we can't do anything on our side as it is not directly related to this project but an issue with npm 😞
