### ISSUE TITLE
Unable to generate component /module or service through cli

### ISSUE THREAD

**Issue by shojibur** [ngx-rocket/generator-ngx-rocket#221]
## I'm submitting a...

[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
Getting following error when trying to generate component through cli 

'Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function'

## Expected behavior
Should able to generate Component

The generator only not working if project generate though ngx-rocket, If i generate normal cli project its working perfectly fine. I am using cli 1.6.5.
I
Any advice or anyone having similar issues ? 

Thanks in advance

**Comment by sinedied** [comment]
Could you share the exact command you are typing?

**Comment by shojibur** [comment]
Hi there, thanks for your prompt reply. I tried following commands 
  ng g c {name-of-component}  , npm run generate {name-of-component} 

Although i found solution which as follows : 
  I realized the problem with @angular-devkit and @schematics, when i using old version of  this i am able to run generator (ng-cli) command without any issue. Working version of those as follows : 
 @angular-devkit-> 
         ->build-optimizer@0.0.31
         ->core@0.0.22
        ->schematics@0.0.42

Some people also reported similar issue here https://github.com/angular/angular-cli/issues/9194 , But it is no more issue if i create project with ng-cli, but if i use ngx-rocket get this issue as mentioned above. 
I am not sure if there are any package need to be update in ngx-rocket.

**Comment by sinedied** [comment]
In your generated project you have a fixed `angular-cli` version that allows only patch updates to avoid build issues: for example it took 5 versions until the `1.6` branch of `angular-cli` properly builds projects, so current version still use the `1.5` branch.

You need to update `angular-cli` manually when wanted/needed in your project, following this procedure (only local package needed when used with `npm run generate`): https://github.com/angular/angular-cli#updating-angular-cli

**Comment by shojibur** [comment]
Thanks for advice, will try.

**Comment by sinedied** [comment]
@shojibur Do you still have issues, or was it related to your angular/cli version?

**Comment by shojibur** [comment]
@sinedied Hi there sorry forgot to update here, it was Angular CLI issues it fixed on recent release. 

Thanks
