### ISSUE TITLE
Ngx update detect app as add-on

### ISSUE THREAD

**Issue by dvaJi** [ngx-rocket/generator-ngx-rocket#226]
## I'm submitting a...
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
When I try to update my app with ngx update i got:

> Make sure you don't have uncommitted changes before overwriting files!
> ? What's the add-on description? (An awesome ngX-Rocket add-on)

## Expected behavior
Should update my application as app and not as add-on

## Minimal reproduction of the problem with instructions
From generator-ngx-rocket 3.1.1 to 3.2.0

## Environment

```
- generator version: 3.2.0
- node version: 8.6.0
- npm version: 5.3.0
- OS:  Windows 10
```

Others:

**Comment by sinedied** [comment]
That's definitely not normal, I'll take a look.
Could you post the content of your `.yo-rc` file?

**Comment by dvaJi** [comment]
Sure:
`{
  "generator-ngx-rocket": {
    "version": "3.1.1",
    "props": {
      "target": [
        "web"
      ],
      "pwa": true,
      "ui": "bootstrap",
      "auth": true,
      "appName": "myapp",
      "projectName": "myapp",
      "packageManager": "npm",
      "mobile": []
    }
  }
}
`

Also I tried with `yo ngx-rocket` and it works perfectly.
