### ISSUE TITLE
HttpCacheService.loadCacheData()

### ISSUE THREAD

**Issue by ausmurp** [ngx-rocket/generator-ngx-rocket#244]
## I'm submitting a...

[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

loadCacheData() currently sets this.cachedData with JSON.stringify(data) which is wrong.

## Expected behavior

Should set this.cachedData with JSON.parse(data)

## Environment
vscode
```
- generator version: 3.2.1
- node version: 8.9.3
- npm version: 5.6.0
- OS: Windows
```

Others:

**Comment by sinedied** [comment]
It was fixed with #237 and already merged on master, it will be available with upcoming release.
