### ISSUE TITLE
Unable to create new project or use any of the ngx commands 

### ISSUE THREAD

**Issue by ivarkallejarv** [ngx-rocket/generator-ngx-rocket#264]
## I'm submitting a...
[x] Bug report

## Current behavior
Generating a new project and updating a project fails with error - 
(node:8572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module 'ignore'
(node:8572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Minimal reproduction of the problem with instructions
npm install -g generator-ngx-rocket
ngx new myProject

## Environment
```
- generator version: 3.2.1
- node version: 8.9.3 
- npm version: 5.7.1
- OS:   Windows
```

**Comment by sinedied** [comment]
Thanks for the report, I don't know how it passed through the CI but the latest `@ngx-rocket/core` update was missing a package, I just pushed an update to fix that.

To make sure you get the updated package, you should `npm remove -g generator-ngx-rocket && ngx install -g generator-ngx-rocket` again.

**Comment by ivarkallejarv** [comment]
Thank you for the quick reaction, seems to be working now. Cheers
