### ISSUE TITLE
--raw option is not working

### ISSUE THREAD

**Issue by carvallegro** [ngx-rocket/generator-ngx-rocket#267]
## I'm submitting a...

[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

When generating the app using the `--raw` option, I'm still asked which UI library I want to use (and it's generated with said library.

## Expected behavior

It is supposed to generate an app using not UI library.

## Minimal reproduction of the problem with instructions

Generate an application using the `--raw` option:
```
ngz new --raw
```

## Environment

```
- generator version: 3.2.1
- node version: 8.9.1  
- npm version: 5.6.0  
- OS:  Mac
```

**Comment by sinedied** [comment]
The option will be available with the next `4.0.0` release, currently on hold due to a last minute bug in `angular-cli` that should be fixed in a few days.
Since the PR have been already merged in `master` the option is present in the docs, sorry for the confusion.
