### ISSUE TITLE
Three (3) packages missing when running starter kit using StackBlitz

### ISSUE THREAD

**Issue by workcontrolgit** [ngx-rocket/generator-ngx-rocket#276]
## I'm submitting a...

[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

When trying to run the Starter Kit using StackBlitz, it reported that 3 packages not found env/environment, app/core and app/shared.

## Expected behavior

Allow to run ngx-rocket starter kit online using StackBlitz

## Minimal reproduction of the problem with instructions

Visit this link:  https://stackblitz.com/github/ngx-rocket/starter-kit

## Environment
https://stackblitz.com

Others:

See below link for more information about usage of StackBlitz (from Angular Blog)

https://blog.angular.io/run-angular-cli-repos-directly-in-your-browser-41332fd80901

**Comment by sinedied** [comment]
There is no missing packages: `@env/environment`, `@app/core` and `@app/shared` are path aliases defined in `tsconfig.json`:
```json
   "paths": {
      "@app/*": ["app/*"],
      "@env/*": ["environments/*"]
    }
```

You should open an issue on StackBlitz, as there is nothing we can do about this on our side.
