### ISSUE TITLE
[Propose] Common module with prefix '@'

### ISSUE THREAD

**Issue by snowyu** [ngx-rocket/generator-ngx-rocket#277]
Make the core and shared etc common modules with prefix '@' and map the path in the `tsconfig.json`.

```js
{
  "compilerOptions": {
    "paths": {
      "@app/*": ["app/*"],
      "@core": ["app/@core"],
      "@shared": ["app/@shared"],
      "@i18n": ["app/@i18n"],
      "@env/*": ["environments/*"]
  }
}
```

Why:

1. Easy to find the common modules(always top in the files).
2. Renamed the folder of the common module does not  affect the codes.

**Comment by sinedied** [comment]
I'm not found of the idea of prefixing path with `@` even if I understand the idea:
- I find it confusing to have `@` for both path aliases and folder names
- Angular's style guide use simply `core` and `shared` module names without prefix, and I prefer using the "recommended" patterns so switching from an Angular project to another feels easier (but I admit it's not a big change)

I usually do not use file explorer in IDE but rather search file by typing the first letters (very efficient in WebStorm or VSCode), so ordering is not an issue but I understand it may helps for others.

**Comment by snowyu** [comment]
* the default path name keep the normal.
* Always import common/genernal modules with the mapping path(to rename easily).
* use an option to enable the prefix '@'.

```js
{
  "compilerOptions": {
    "paths": {
      "@app/*": ["app/*"],
      "@core": ["app/core"],
      "@shared": ["app/shared"],
      "@i18n": ["app/i18n"],
      "@env/*": ["environments/*"]
  }
}
```

**Comment by sinedied** [comment]
Seems reasonable to use a command line option for this like `--common-prefix=@` and it should already work as aliases are already used everywhere for `core`, `shared` and `env` folders.

I'm wondering though, what do you put in the `i18n` folder? The translations?

**Comment by snowyu** [comment]
The i18n service, the language switcher component and language constants.

**Comment by sinedied** [comment]
I'm bouncing back on this issue as I ended up adding `@` prefix on core/shared module like you suggested in my projects, as it's useful when the app/ folder becomes cluttered with many components 😄 

I'll see what I can to add the command line option for this, as I predict that some may prefer their own prefix (`!`, `_` or whatever...)

**Comment by robertmansion** [comment]
@sinedied question, what about the shell folder?

**Comment by sinedied** [comment]
@robertmansion The shell is for me like any other regular component, with its own feature folder so there's no need IMHO for an `@` alias. But if you would like, you can always add more in your project as you need.
