### ISSUE TITLE
Publish to gh-pages

### ISSUE THREAD

**Issue by reflexdemon** [ngx-rocket/generator-ngx-rocket#278]
Hey,

## I'm submitting a...

[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request

I am looking for some help in publishing or deploy web application on to `gh-pages`. Often times, it will be useful for people who can quickly generate the application and then publish it on github to test the PWAs on their mobile devices for quick demos etc.

## Current behavior
I am having to tweak the generated code to publish the code to github pages.
Here is the list of steps that I did to get it working.
1. Update the `.gitignore` to remove `dist` folder to the git repo
2. On `index.html` I had to replace the base with `<base href="./" />`. This is because the web application when running on `gh-pages` does not always start with `root` context. Which means `/` is not going to work on `gh-pages`.
3. Update the `ServiceWorkerModule` imports on the `app.module.ts`.

*From*:
```
ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.production }),
```
*To*:
```
ServiceWorkerModule.register('./ngsw-worker.js', { enabled: environment.production }),
```
This is also to make sure the worker is working on `gh-pages`.

## Expected behavior
I had to do it without any tweaks and make it simple for users to be able to publish the pages on github.

## Minimal reproduction of the problem with instructions
Run the following after the scaffolding is complete on your project home directory.
```
$ npm run build --env=prod
...
$ git subtree push --prefix dist/ origin gh-pages
git push using:  origin gh-pages
No new revisions were found
```

## Environment
```
$ which ngx                                                                                                                                   1 ↵
~/.npm-global/bin/ngx

$ ngx -version
          __   __
 _ _  __ _\ \./ / ____ ____ ____ _  _ ____ ___
| ' \/ _` |>   <  |--< [__] |___ |-:_ |===  |
|_||_\__, /_/°\_\ ENTERPRISE APP STARTER -~*=>
     |___/ v4.0.0

$ node --version                                                                                                                              1 ↵
v8.10.0
$ npm --version
5.6.0
$ uname -srvpio
Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 GNU/Linux
```

## Others
Here is the link to the one I had just tried to publish on `gh-pages`. https://pwa.vpv.io
If this issue is accepted I don't mind submitting PR for the same.

**Comment by sinedied** [comment]
The base routing configuration is made to work purely in HTML5 mode and needs a web server [configured for it](https://github.com/ngx-rocket/starter-kit/blob/master/docs/routing.md).

In the upcoming version, the `--location-path=hash` option will allow you to use AngularJS hashbang-style routing which works with web server not supporting HTML5 routing properly, such as github pages.

Using `./` for base-href import do not work if you hit F5 when you already navigated to another page or with more complex sub-routing, so it's still not ideal.

As for the `dist` folder being excluded it's a safe default, and changing it is not needed for publishing to gh-pages. You can use https://github.com/tschaub/gh-pages or https://github.com/angular-schule/angular-cli-ghpages to publish directly your `dist` folder, even as part of your NPM scripts.

For the service worker, it would need some testing (especially for the mobile use-cases) but I think it would be harmless to change it to `./` by default as it should always be in the same folder as the `app.js` bundle.

On another note, it would be a great fit for an addon like https://github.com/ngx-rocket/addon-firebase to prepare the scripts and the changes needed to deploy to gh-pages 😃

**Comment by reflexdemon** [comment]
Sure. Thanks for the `gh-pages` suggestion and I am waiting for `hash-path` option.

Let me give a try for the service worker PR.

As I was going over the documentations on the generator I am more attracted and feeling good about it. Great work guys! Let me wait to understand the addons and if I think I am in hold of it, I will submit a addon.

**Comment by sinedied** [comment]
Supported with #542
