### ISSUE TITLE
https://stackblitz.com/github/ngx-rocket/starter-kit not working

### ISSUE THREAD

**Issue by workcontrolgit** [ngx-rocket/generator-ngx-rocket#280]
## I'm submitting a...

[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

Error when running the starterkit with stackblitz

Can't find packages:
@env/environment@app/core@app/shared

## Expected behavior

Successfully run StarterKit online

## Minimal reproduction of the problem with instructions

Visit https://stackblitz.com/github/ngx-rocket/starter-kit 

For background information, visit https://blog.angular.io/run-angular-cli-repos-directly-in-your-browser-41332fd80901 

## Environment

```
- generator version: X.Y.Z
- node version: X.Y.Z  <!-- run `node --version` -->
- npm version: X.Y.Z  <!-- run `npm --version` -->
- OS:  <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment]
See my answer in https://github.com/ngx-rocket/generator-ngx-rocket/issues/276

You should open an issue on StackBlitz, as there is nothing we can do about this on our side, they just do not support typescript path aliasing which is used in a lot of Angular projects out there.
