### ISSUE TITLE
How to change default page

### ISSUE THREAD

**Issue by mahnuh** [ngx-rocket/generator-ngx-rocket#297]
Hi,

I am trying to change the default page when logged in from home to about (or any other newly created page) but I seem to miss something as I am not getting it to work.
I replaced about with home in app-routing.module.ts and switched the corresponding lines in about-routing.module and home-routing.module. What am I missing?

Thanks in advance for any help with this!

**Comment by sinedied** [comment]
Look at the login component:
```ts
 login() {
    this.isLoading = true;
    this.authenticationService.login(this.loginForm.value)
      .pipe(finalize(() => {
        this.loginForm.markAsPristine();
        this.isLoading = false;
      }))
      .subscribe(credentials => {
        log.debug(`${credentials.username} successfully logged in`);
        this.router.navigate(['/'], { replaceUrl: true }); // <<< Replace route here
      }, error => {
        log.debug(`Login error: ${error}`);
        this.error = error;
      });
  }
```
When the login is successful, this is the line ` this.router.navigate(['/'], { replaceUrl: true });` that redirect to home by default. You can change it to whatever page you want here.

**Comment by ultrarunner** [comment]
I have a similar question. When you say that " the line this.router.navigate(['/'], { replaceUrl: true }); that redirect to home by default", can you please elaborate? I am trying to force all users that navigate to the root, i.e. '' to be redirected to 'home' by default but I cannot figure out where that is happening. I have enabled tracing on on the app-routing.module.ts file but I still don't understand how it works. Thank you.

**Comment by sinedied** [comment]
> I have a similar question. When you say that " the line this.router.navigate(['/'], { replaceUrl: true }); that redirect to home by default", can you please elaborate?

This is only regarding the login component and page you're redirected to once you are logged.

To set a default route that redirects to `/home`, just add the line you posted but in `home-routing.module.ts`, see https://github.com/ngx-rocket/starter-kit/blob/master/src/app/home/home-routing.module.ts#L9-L10

But make sure your feature modules (home, about, etc) routing modules are imported in the `app.module.ts` file *before* the AppRoutingModule, which contains a catch-them-all fallback to redirect on whatever page you want (by default, `''`), see https://github.com/ngx-rocket/starter-kit/blob/master/src/app/app-routing.module.ts#L6

**Comment by sinedied** [comment]
@mahnuh If this is solved for you, can you close the issue?

**Comment by byronglendon** [comment]
I am still having a problem after making the above changes.
If the user was previously logged in and opens the page on http://localhost:4200/
The navbar shows but the content page is that of app.component.html
Any assistance would be appreciated.

This project was generated with [ngX-Rocket]
version 7.0.2
