### ISSUE TITLE
Make api prefix interceptor optional

### ISSUE THREAD

**Issue by FranciZ** [ngx-rocket/generator-ngx-rocket#300]
## I'm submitting a...
- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior
When making requests with HttpClient the api prefix interceptor always prefixes the server url. This prevents the app from making any requests to external services.

## Expected behavior
Would be great to add an option that would disable the prefix.

**Comment by sinedied** [comment]
Sure, instead of having it for all requests, it could be made optional like other interceptors, the modification is trivial.

Just in case, to disable it for all requests you just have have to remove this from `core.module.ts`:
```ts
    {
      provide: HTTP_INTERCEPTORS,
      useClass: ApiPrefixInterceptor,
      multi: true
    },
```

**Comment by pablovelezvidal** [comment]
what are the reasons that make it a "good thing" to have an http interceptor? what if my app is not just communicating to one api but several? how should the interceptor work?

**Comment by bursauxa** [comment]
If you are doing full-stack development (i.e. you are building both the front-end and back-end), which is a common scenario for an Angular application, then a large majority of the requests performed with $http will call the same API: namely, *your* API.

Even if your back-end is not a singular back-end but a whole bunch of micro-services, these services should still be behind at least one layer of reverse-proxying, which means that from the outside they look like one single service (i.e. only one root URL).

However, even though there is only one API at a given time, its location is subject to change. Typically, it will not be located at the same place when you are hosting it on your developer's computer, on an integration environment, in production etc. The prefix interceptor frees you from changing all your routes everywhere when switching environments.
