### ISSUE TITLE
Migrate to Ionic@4

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#302]
Ionic 4 will be a major change as the framework will be completely rewritten as web components with the new v4 version.

It's currently available for testing, so we must make sure that once v4 is out we are ready to migrate to it.

**Comment by captaincaius** [comment]
Hi.

I followed the migration guide to ionic 4 on a virgin generated ngx-rocket and made a PR against it to get an idea of the big picture of what would be involved for this issue.

I tried to use my best judgment whenever it was unclear whether a given change was contrary to your goals for this project, but there were still a few instances that I wasn't sure about (e.g. styling structure).

It's not fully done yet, but now that it loads, I wanted to run it by you first to see if it would be helpful to you for me to take it to completion.  If not, it's no biggie - I wanted to use this as an exercise in the port anyway.

Let me know if you think it's worth the trouble of continuing :)

**Comment by captaincaius** [comment]
Lol forgot to paste the link :P

https://github.com/captaincaius/ngxrocket501toionic4beta/pull/1/files

**Comment by sinedied** [comment]
Hi @captaincaius, I'll take a look but you can also try comparing/helping @iocaste on this PR as he also started working on it: https://github.com/ngx-rocket/generator-ngx-rocket/pull/358

**Comment by captaincaius** [comment]
Thanks! :) Will do.

**Comment by captaincaius** [comment]
PR here: #369

**Comment by bursauxa** [comment]
Closing this issue as the PR was merged. Thanks for your work 👍
