### ISSUE TITLE
build doesn't works

### ISSUE THREAD

**Issue by gbarrionuevo** [ngx-rocket/generator-ngx-rocket#314]

**Comment by mkwsra** [comment]
It's the same in my case as well, it's giving a white screen only, which is normal since in console it's printing out that dependencies aren't found like `styles.xxxxxx.css` and _js_ as well!

**Comment by sinedied** [comment]
@gbarrionuevo Sorry but we cannot help you if you do not fill in the issue template, such as you node/npm version, OS, generator version, etc.
