### ISSUE TITLE
Ionic Tabs not working

### ISSUE THREAD

**Issue by darron1217** [ngx-rocket/generator-ngx-rocket#317]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

Ionic Tabs not Showing
(Tab bar exists, but not showing)
template.component.html
```html
      <ion-tabs tabsPlacement="top">
          <ion-tab [root]="photoTab" tabTitle="샘플사진" tabIcon="md-images"></ion-tab>
          <ion-tab [root]="layoutTab" tabTitle="레이아웃" tabIcon="md-albums"></ion-tab>
          <ion-tab [root]="backgroundTab" tabTitle="배경" tabIcon="md-image"></ion-tab>
          <ion-tab [root]="clipartTab" tabTitle="클립아트" tabIcon="md-cloud-outline"></ion-tab>
      </ion-tabs>
```
template.component.ts
```typescript
@Component({
  selector: 'app-template',
  templateUrl: './template.component.html',
  styleUrls: ['./template.component.scss']
})
export class TemplateComponent implements OnInit {

  photoTab = PhotoComponent;
  layoutTab = LayoutComponent;
  backgroundTab = BackgroundComponent;
  clipartTab = ClipartComponent;

  constructor() {

  }

  ngOnInit() {

  }

}

```
photo.component.html
```
<p>
  photo works!
</p>
```
![image](https://user-images.githubusercontent.com/8064923/39741205-de5b8b48-52d3-11e8-81bf-9ea6dd09406d.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/8064923/39741322-738f22b0-52d4-11e8-9967-4aefa1a91414.png)

## Environment

```
- generator version: X.Y.Z
- node version: X.Y.Z  <!-- run `node --version` -->
- npm version: X.Y.Z  <!-- run `npm --version` -->
- OS:  <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment]
You should try StackOverflow or the ionic forum (https://forum.ionicframework.com), as it's more a question related to Ionic than this generator.
We already used tabs without issues, you can try looking at the `ionic-tabs` branch here https://github.com/ngx-rocket/starter-kit/tree/feature/ionic-tabs, but keep in mind that it's a WIP.

**Comment by darron1217** [comment]
I was dumb... It was my mistake..

I didn't put `ion-content` on photo component. And it made Tabs inactive
Tabs example helped me a lot :) 
Thanks
