### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by ChristofDC** [ngx-rocket/generator-ngx-rocket#320]
## I'm submitting a...

- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
running ngx new to create a new project results in following error:
```
Template processing error on file .editorconfig
events.js:167
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files (x86)\Nodist\bin\node_modules\generator-ngx-rocket\generators\app\templates\.editorconfig
```

## Expected behavior
new project gets created

## Minimal reproduction of the problem with instructions
```
C:\source\projects\ngx-starter>ngx new
          __   __
 _ _  __ _\ \./ / ____ ____ ____ _  _ ____ ___
| ' \/ _` |>   <  |--< [__] |___ |-:_ |===  |
|_||_\__, /_/°\_\ ENTERPRISE APP STARTER -~*=>
     |___/ v4.2.0

(node:12620) ExperimentalWarning: The fs.promises API is experimental
? What's the name of your app? ngx app
? What kind of app do you want to create? Web app
? Do you want a progressive web app? (with manifest and service worker) Yes
? Which UI framework do you want? Angular Material (more website-oriented)
? Which kind of layout do you want? Simple responsive header bar (more website-oriented)
? Do you want authentication? Yes
? Do you want lazy loading? Yes
? Do you want analytics support (with Angulartics2)? No
```

## Environment

```
- generator version: 4.2.0
- node version:  10.1.0 <!-- run `node --version` -->
- npm version: 4.0.5  <!-- run `npm --version` -->
- OS:  Windows
```

Others:
Using Nodist as node version manager. Was never any issue before.

**Comment by sinedied** [comment]
Your npm version seems strange, as starting from node@8 the minimum supported version is npm@5.

One thing I noticed on your error is the path with a space inside "Program Files", when standard nodeJS put packages in %appdata% where there should be no spaces, and I know that NodeJS apps may have issues with spaces in path on Windows.

Nodist isn't maintained for 2 years now, I suggest you to use https://github.com/coreybutler/nvm-windows as an alternative, I never had an issue with it and I know that this generator does work with it.

**Comment by ChristofDC** [comment]
thanks! that was indeed the issue.
Changed to nvm-windows and that version manager maintained the npm version as well.
