### ISSUE TITLE
Downgrade to Angular4

### ISSUE THREAD

**Issue by arunprasathgajapathi** [ngx-rocket/generator-ngx-rocket#321]
I want to generate Angular4 project using ngx-rocket, anyway to downgrade to angular4 and generate the project ?

**Comment by sinedied** [comment]
There's no way to downgrade projects, however you can use an older version of the generator: `2.3.1` was the last version using Angular 4, you should try it.

**Comment by arunprasathgajapathi** [comment]
Yeah .i tried with installing 2.3.1 generator, i got only angular 5 instead of angular 4. I don't know why happen like that..any suggestions?

Tried to clean entire npm cache and reinstall ngx-generator@2.3.1 too..but nothing works.i tried with downgrading ngx-cli version too..still getting angular 5 in package.json.

**Comment by arunprasathgajapathi** [comment]
But when i download from github in release i can see the package.json with angular 4. Anyway to generate it from that zip file?
