### ISSUE TITLE
Configure H5's application local cache'Application Cache'

### ISSUE THREAD

**Issue by leihg** [ngx-rocket/generator-ngx-rocket#324]
Can the application local cache be configured? 'Application Cache', like this `'<html manifest= "demo.appcache" > "?`

**Comment by sinedied** [comment]
This is an obsolete feature that was removed from the web standards, see https://developer.mozilla.org/fr/docs/Web/HTML/Utiliser_Application_Cache.

You should enable PWA option that use a service worker to provide the same functionality instead.

**Comment by bursauxa** [comment]
Same link in English, in case you want details: https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

Fundamentally the proper answer is as @sinedied said, use service workers instead.
