### ISSUE TITLE
Passing a template to ngx raw project

### ISSUE THREAD

**Issue by ChristianGalvez23** [ngx-rocket/generator-ngx-rocket#325]
Hello everyone,

I bought a template and I passed all scripts and styles in the NGX Structure and all works but fonts don't work when I compile the application.

The template has a style.scss where imports a font from Google API.

`@import url(https://fonts.googleapis.com/css?family=Dosis:400,600,700|Great+Vibes);`

I compiled the application with the command `npm run build` but I think the proccess ignore the import that in dist folder doesn't appear the font.

What do you suggest me guys?

**Comment by sinedied** [comment]
The import works well, but it's not supposed to be present in your build folder as this syntax is for dynamic imports: the font will be loaded directly from google servers, even in your prod build.

If you want to package the font with your app, you have to download it from google font along with the css, and put it in your app sources.

**Comment by bursauxa** [comment]
Closing this as we haven't heard more from @ChristianGalvez23, and @sinedied's answer seems to be spot on.
