### ISSUE TITLE
Add "Dockerize your angular app" option to the setup wizard. 

### ISSUE THREAD

**Issue by kenan435** [ngx-rocket/generator-ngx-rocket#327]
I would like to be prompted in the ngx setup wizard if I would like to "Dockerize" the angular app. This would create docker files for dev and production. In the case of prod; ask which prod web server I would like to use (Apache, nginx etc...). We could have a task (npm start --docker) which builds the image and runs it inside of a docker container mounting the local src, node_module folders so that we can hot-reload changes while writing our app.

## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behaviour

Currently there is no support for dockerizing angular apps.

## Expected behaviour

Would like to automate the Dockerzing of angular app for dev and prod purposes.

**Comment by sinedied** [comment]
Sure that would be nice, I think it would be a great fit for an add-on 👍

**Comment by kenan435** [comment]
OK, i'll take it...

**Comment by duydnguyen07** [comment]
@kenan435 Are you thinking of using nginx to host the app container or expressJs, or something else?

**Comment by sinedied** [comment]
Closing this one, as it seems official support via ng CLI is coming: https://github.com/angular/angular-cli/blob/master/docs/design/docker-deploy.md

**Comment by AndreKoepke** [comment]
@sinedied your link is dead. I think, they moved the functionality to [ngx-deploy-docker](https://www.npmjs.com/package/ngx-deploy-docker), but I found no documentation about it. Only this commit: https://github.com/angular/angular-cli/commit/245e669d631eabf3476169aa6e9208766503bcd6

Maybe rocket can just add the `ngx-deploy-docker`?

**Comment by sinedied** [comment]
This might be a good idea, since official support seems to have been dropped.
Are you willing to submit a PR for it?

This could be added to other deployment option, and as `ngx-deploy-docker` supports `ng add` it should be a straightforward addition.

**Comment by AndreKoepke** [comment]
I'm discovered `ngx-rocket` and `ngx-deploy-docker` today for the first time.  :D
I will try it, but I can't make any promises.
