### ISSUE TITLE
Question : Auth - add Header Bearer

### ISSUE THREAD

**Issue by Paul75** [ngx-rocket/generator-ngx-rocket#329]
Hello,

I want to know when I can add into request http the token into a Bearer (in header) of request ?

Thanks

**Comment by creal73** [comment]
Hi,

You can use an **HttpInterceptor** to add the right header in the request based on **AuthenticationService** 

Here is a [useful link](https://ryanchenkie.com/angular-authentication-using-the-http-client-and-http-interceptors)

**Comment by Paul75** [comment]
Thanks for give me this exemple :)

**Comment by Paul75** [comment]
But When I do like and add Intereptor in CoreModule : 
```
{
      provide: HTTP_INTERCEPTORS,
      useClass: TokenInterceptor,
      multi: true
    }
```

and do this : 
```
@Injectable()
export class DatasService {
  private _credentials: Credentials | null;

  constructor(private http: HttpClient, private authenticationService: AuthenticationService) {
  }

  getAllDatas(): Observable<any> {
    this._credentials = this.authenticationService.credentials || null;

    if (this.authenticationService.credentials) {
      const token = '?token=' + this._credentials.token;

      // return this.http.get('/datas' + token);
      return this.http.get('/datas');
    }
  }
}
```

Nothing add into header ...

Thanks
