### ISSUE TITLE
CLI and composition with other possible addons generators

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#33]
Once #6 is done, a welcome suggestion (thanks @R0muald) was to provide a way to compose the base SK generator with any other "addon" generators.

One way could be to investigate yeoman's [composability features](http://yeoman.io/authoring/composability.html) or maybe create a custom CLI to simply wraps the generators setup/install/running.

The basic idea is to gather in a simple way for the user the ability to mix the SK with addon generator, something like:
```sh
$ ngx new myAwesomeProject --addons="myCompanyUiLibrary someBackendGenerator"
```
or even maybe
```sh
 # performs `npm install` + register addons with ngx cli
$ ngx addon install myCompanyUiLibrary someBackendGenerator
# registered addons will be used by default
$ ngx new myAwesomeProject
```

Yeoman also support generating a project from multiple generators, so we should also consider this.

# Remaining tasks

- [x] Extract generator code in a separate package
- [x] Add template prefix to allow merging json files
- [x] Refactor base generator to use core
- [x] Create an example addon generator
- [x] Create CLI
- [x] Create generator for making addons
- [x] Add documentation
- [x] Create new issues for blueprints support...

**Comment by R0muald** [comment]
Great job with the Yeoman generator! between the authentication flow and the dependencies installation, it's very well done!

I'm currently looking into possible ways to extend your generator with something that would let me configure the generated architecture to:
- Modify package.json with companyLibs dependencies
- Replacing header and home page with company components (html and module)
- Modify Authentication template if part of the generated architecture...

After looking at yeoman's composability features, I think one possibility could be to create a generator that would have generator-ngx-app as dependency, then use 
```
this.composeWith(require.resolve('generator-ngx-app/generators/app'));
```
Part of the generator-corp-app process.
So calling:
```
yo corp-app
```
Would actually run ngx-app then run the company generator to extend and modify your architecture.

Do you think that would be an efficient way to achieve what I'm looking for? 
My main concern is related to the high dependence between the generated folder structure with your generator and the modification of those files/folder with the company generator... Maybe only overwriting the app folder could simplify the process...

Or maybe, would a fork of the ngx-app generator be a better solution for that? ( not fond of that since it would require me to keep updating the corp-app generator with every update/fix you do part of this project...)

What do you think?

**Comment by sinedied** [comment]
Your concerns are exactly what I've given a lot of thoughts these last weeks 😉 

My opinion is that you should do neither of your solutions.
My vision on this is that addon/composed generators should never have to deal with upgrades regarding to the ngx generation evolutions. It should be really easy to create a new addon generator, to favor composition of small generator pieces. Finally, any number of addon generators could be used to generate a project.

To do so, just using Yeoman's composition won't be enough, because:

- You can't use prompts or options from other generator, so you may end asking the same question multiple time ("do you want a web or mobile app?" "use Ionic or Bootstrap?" etc)

- You have to learn Yeoman API and keep the generator synchronized on the same version to avoid issue.

- You have to make your own template generation logic. A lot of template generation logic will probably end up being duplicated. Moreover, there's no "easy" way to merge/update files from other generators.

What I'm planning to do is to extract all the core generator/template logic of the ngx generator into a separate npm module. By doing so, instead of extending a "bare" Yeoman generator when creating your own, you will be extending the ngx generator instead, and getting all its benefits: the prompts options, the template logic, the merging/update logic, all will be included.
Better, if you do no plan to do anything fancy in you generator but replace/update templates and dependencies, your generator's code will be just this:
```js
const Generator = require('ngx-base-generator');
module.exports = class extends Generator {}
```

#### Then how to run/use the addon generators?
This is actually the actually the tastier part, since it seems Yeoman's team seems to already have envisioned the creation of generator ecosystem, using their [yeoman-environment](https://github.com/yeoman/environment): this is what is used under-the-hood by the `yo` CLI, and this is what we will use to create our own `ngx` CLI 😀 

The only constraint is that ngx addon generator will need to be named with a common prefix, like `generator-ngx-addon-your-corp`. By doing so, `yeoman-environment` is able to detect and filter those generators and we can do the composition of any number of addon generators.

Using it will be as simple as:
```
$ npm install -g ngx-cli generator-ngx-addon-your-corp
$ ngx new <project_name>   # will use all locally installed generator-ngx-addon-*
```

Would that solution be ok with your needs?

**Comment by R0muald** [comment]
I think that would be perfect! 
Having an external CLI will also make it easy to add corporate module directly inside the code that could be done through the CLI prompt like:
```shell
$ ngx add module  # will list all module that can be added to the current project (authentication / translate / corporate_speicific_module ...)
$ ngx add component # will replace `ng g component` with corporate template component that could change if working on a mobile / web project
```

Also, I just have a small concern about the way you add the ngx-addon. As I can see in your example, as soon as you add one, it will be used everytime. So basically a user that install once the corp addon, will only be able to generate corp app. Not sure it's a problem on my side but is there a way to manage / remove those addons if the user does not want to use them anymore?

**Comment by sinedied** [comment]
For your concern, yes we must also think of a way to enable/disable addons depending of the user needs. Maybe it's just a matter of a `ngx setup` command for example, that would list all installed addon and where we could check/uncheck them individually.
I thought that by default it would be better to use all installed addon for convenience, but that is debatable :)
It's something that can still be improved/changed in a second time I think, after getting some feedback .

**Comment by sinedied** [comment]
For those interested, the [CLI](https://github.com/ngx-rocket/cli) is fully working working at this point. By default, all locally installed addon generators are used, but you can enable/disable them individually with `ngx config`. 

A basic [addon example](https://github.com/ngx-rocket/addon-example) is also ready and published to play with.

Now there's a lot of documentation to write for it, and I'll finish with an addon boilerplate generator to make addon creation even easier 😄 

Any feedback is welcome!

**Comment by sinedied** [comment]
Finally!! 🎉 👯 🍾 

A lot efforts went in this, but it's done 😃 

See the docs and tools in:
- https://github.com/ngx-rocket/core
- https://github.com/ngx-rocket/generator-ngx-rocket-addon
- https://github.com/ngx-rocket/cli
- https://github.com/ngx-rocket/addon-example
