### ISSUE TITLE
How can I add jQuery to the generated project?

### ISSUE THREAD

**Issue by rvalenciano** [ngx-rocket/generator-ngx-rocket#330]
## I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

## Current behavior

I'm trying to add [surveyjs](https://github.com/surveyjs/surveyjs_angular_cli) to this 
project. Their example relies in an angular-cli application. I've reached the point where I need to add jquery to the project but I'm not able to. I constantly get the error:

```
Uncaught TypeError: Cannot read property 'fn' of undefined
    at Object.widgetIsLoaded (surveyjs-widgets.js:88)
```

Which after investigation you can figure it out that is related to jquery not being loaded.

Checking their example project and looking for jquery:

<img width="450" alt="screen shot 2018-06-05 at 9 31 25 am" src="https://user-images.githubusercontent.com/5366444/40986379-480a9f2c-68a3-11e8-95f8-e1db970b4313.png">

<img width="471" alt="screen shot 2018-06-05 at 9 31 37 am" src="https://user-images.githubusercontent.com/5366444/40986387-4c0b28c6-68a3-11e8-9ecc-34ee64c7afed.png">

I only see missing the `angular-cli.json` file in the ngx-rocket project, which is the equivalent of this file?

## Expected behavior

To add jquery to the project so I can successfully add surveyjs.

## Environment

```
- generator version: 5.0.0
- node version: v8.9.4
- npm version: 5.6.0
- OS:  Mac
```

Others:

N/A

**Comment by sinedied** [comment]
`angular-cli.json` was used before Angular 6, now the equivalent is `angular.json`.
If you add the jquery script to the `scripts` property there it should be enough, you do not need to add anything to `polyfills.ts` as it would just duplicate the code and import jquery a 2nd time.

**Comment by bursauxa** [comment]
@rvalenciano did this solution work for you?

**Comment by rvalenciano** [comment]
Yes @bursauxa , sorry for not reaching back.
