### ISSUE TITLE
Nested CRUD routing isn't working.

### ISSUE THREAD

**Issue by iocaste-forks** [ngx-rocket/generator-ngx-rocket#334]
## I'm submitting a...

- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

Can't get parameters from nested routes. Tried in several ways, but can't get parameters from routes with current project setup.

Run project and go to /messenger route. There is button "Chat with" witch redirects to /messenger/:id route. You will be redirected to /messenger/uuid_12345678901234567890 but route parameter will always be empty. In chat.component.ts there is variable mateUuid, which will be empty, but should contain uuid_12345678901234567890

## Expected behavior

1. Browse to /messenger route, then press "Chat with" button. 

2. You should be redirected to route:
/messenger/uuid_12345678901234567890 

3. See text: **ID from route param: uuid_12345678901234567890**

## Minimal reproduction of the problem with instructions

Project demo:
[Example github repo](https://github.com/iocaste/ngx-example)

## Environment

```
- generator version: 5.0.0
- node version: v9.6.1
- npm version: 5.10.0
- OS:  OSX
```

Others:

**Comment by wnabil** [comment]
If you only want to receive the data and don't care about the url you can make a navigation data service and store your params in it and receive them in the next component, it depends on your app requirements but just in case if you need a fast fix until the owners reply to you.

**Comment by sinedied** [comment]
Just took a quick look and I could reproduce the issue, it seems that `ActivatedRoute` always returns the root component instead of the expect "routed" component.
Seems that it's a regression of Angular 6, as with an Angular 5 project I did the same and it worked as expected.
You should make a simple [StackBlitz](https://stackblitz.com/) reproduction of the issue and file a bug on Angular repo.

**Comment by iocaste** [comment]
@sinedied I have same thing with angular 5.2 and your older ngx-rocket pack.

**Comment by sinedied** [comment]
@iocaste My bad, I tested with `v4.2.0` in the meanwhile and I could reproduce the issue.
As is seems, the working version I had used Angular Material and not Ionic, and it seems that's the catch here: Ionic wraps the Angular app and that seems to perturbate the Angular router somehow.
I hope that with their upcoming `4.0.0` release that was announced to be angular CLI-compatible those issue will be resolved 😞 

In the meanwhile, the best workaround I can think of is to manually search the router tree to find the expected route, and put the function in a helper service.

**Comment by iocaste** [comment]
@sinedied As ionic 4 now is in beta status, maybe work on porting new routing can be started ?

[https://blog.ionicframework.com/announcing-ionic-4-beta/](https://blog.ionicframework.com/announcing-ionic-4-beta/)

**Comment by sinedied** [comment]
@iocaste Yes, but there's a some issues that needs to be done first so it works well, like https://github.com/ngx-rocket/generator-ngx-rocket/issues/231 and https://github.com/ngx-rocket/generator-ngx-rocket/pull/335 

Will work on it, but it might not be very fast as everyone is busy on the beach these days :wink:

**Comment by iocaste** [comment]
@sinedied As for now generator with current v3 ionic, that is supported, isn't usable. I have tried to port generators to v4 ionic but looks like very massive work should be done and it requires expert knowledge of generator package 😄 

I looked into #335 and to accept it now would be useless (you can't build normal application with routing bug). My opinion is that PR should be rewritten for v4 and accepted on ionic v4 branch

**Comment by sinedied** [comment]
This should not be an issue anymore, as the old routing plugs were removed after v4 migration. Feel free to reopen if that's not the case.
