### ISSUE TITLE
Data path ".baseHref" should be string.

### ISSUE THREAD

**Issue by adappter** [ngx-rocket/generator-ngx-rocket#336]
Hey there,

I need some support preparing/running a cordova app.

## I'm submitting a...
- [x ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
Schema validation failed with the following errors:
  Data path ".baseHref" should be string.

## Expected behavior

Cordova should run app

## Minimal reproduction of the problem with instructions
Run: npm run cordova:prepare or npm run cordova run android

## Environment
```
- generator version: 5.0.1
- node version: 8.9.3
- npm version: 6.1.0
- OS:  macOS
```

**Comment by sinedied** [comment]
Please fill in issue template, otherwise we cannot help you as do not know on which environment you're having this issue.

**Comment by adappter** [comment]
done

**Comment by sinedied** [comment]
Thanks, I'll take a look it's definitely not normal

**Comment by sinedied** [comment]
I tried with the same environment and could not reproduce the issue.
Seems like an error that could be due to a module version mismatch, you can try:
```
rm -rf node_modules/
npm remove -g @angular/cli
npm cache clean --force
npm install
```
If you still have the issue, please post your answers to the generator questsions and the result of `npm ls --depth=0` and `npm ls -g --depth=0`.

**Comment by adappter** [comment]
npm ls --depth=0

`├── @angular-devkit/build-angular@0.6.7
├── @angular/animations@6.0.3
├── @angular/cli@6.0.7
├── @angular/common@6.0.3
├── @angular/compiler@6.0.3
├── @angular/compiler-cli@6.0.3
├── @angular/core@6.0.3
├── @angular/forms@6.0.3
├── @angular/http@6.0.3
├── @angular/language-service@6.0.3
├── @angular/platform-browser@6.0.3
├── @angular/platform-browser-dynamic@6.0.3
├── @angular/pwa@0.6.8
├── @angular/router@6.0.3
├── @biesbjerg/ngx-translate-extract@2.3.4
├── @ionic-native/core@4.7.0
├── @ionic-native/keyboard@4.7.0
├── @ionic-native/splash-screen@4.7.0
├── @ionic-native/status-bar@4.7.0
├── @ngx-rocket/scripts@2.1.0
├── @ngx-translate/core@10.0.2
├── @types/jasmine@2.8.8
├── @types/jasminewd2@2.0.3
├── @types/lodash@4.14.109
├── @types/node@8.10.18
├── codelyzer@4.3.0
├── cordova@8.0.0
├── cordova-android@7.1.0
├── cordova-custom-config@5.0.2
├── cordova-ios@4.5.4
├── cordova-plugin-device@2.0.2
├── cordova-plugin-ionic-webview@1.2.1
├── cordova-plugin-splashscreen@5.0.2
├── cordova-plugin-statusbar@2.4.2
├── cordova-plugin-whitelist@1.3.3
├── core-js@2.5.7
├── hads@1.6.1
├── htmlhint@0.9.13
├── https-proxy-agent@2.2.1
├── ionic-angular@3.9.2
├── ionic-plugin-keyboard@2.2.1
├── ionicons@3.0.0
├── jasmine-core@2.99.1
├── jasmine-spec-reporter@4.2.1
├── karma@2.0.2
├── karma-chrome-launcher@2.2.0
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@1.4.3
├── karma-jasmine@1.1.2
├── karma-junit-reporter@1.2.0
├── lodash@4.17.10
├── ng-busy@6.0.0-rc0
├── protractor@5.3.2
├── puppeteer@1.4.0
├── UNMET PEER DEPENDENCY rxjs@6.2.0
├── rxjs-compat@6.2.0
├── stylelint@9.2.1
├── stylelint-config-recommended-scss@3.2.0
├── stylelint-config-standard@18.2.0
├── stylelint-scss@3.1.0
├── ts-node@6.0.5
├── tslint@5.10.0
├── typescript@2.7.2
└── zone.js@0.8.26

npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/core@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/keyboard@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/splash-screen@4.7.0
npm ERR! peer dep missing: rxjs@^5.0.1, required by @ionic-native/status-bar@4.7.0
`

npm ls -g --depth=0
├── cordova@8.0.0
├── cordova-check-plugins@4.0.2
├── cordova-icon@0.9.1
├── cordova-plugin-update@0.1.0
├── cordova-splash@0.9.0
├── generator-ngx-rocket@5.0.1
├── http-server@0.11.1
├── imagemagick@0.1.3
├── ionic@3.20.0
├── ionic2-custom-icons@0.5.1
├── ios-deploy@1.9.2
├──  error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/ios-sim/package.json
├── live-server@1.2.0
├── n@2.1.8
├──  error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/nativescript/package.json
├── npm@6.1.0
├── npm-check-updates@2.13.0
├── npm-upgrade@1.2.0
├── plugman@2.0.0
├── rxjs-tslint@0.1.3
├── splashicon-generator@0.2.12
├── tsd@0.6.5
├── UNMET PEER DEPENDENCY tslint@^5.0.0
├── typings@2.1.1
└── web-push@3.3.1

npm ERR! peer dep missing: tslint@^5.0.0, required by rxjs-tslint@0.1.3
npm ERR! error in /usr/local/lib/node_modules/ios-sim: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/ios-sim/package.json'
npm ERR! error in /usr/local/lib/node_modules/nativescript: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/nativescript/package.json'
npm ERR! missing: ref@https://github.com/icenium/ref/tarball/v1.3.2.3, required by ffi@2.0.0
npm ERR! missing: ref-struct@https://github.com/telerik/ref-struct/tarball/v1.0.2.5, required by ffi@2.0.0
npm ERR! missing: prebuilt@https://github.com/tailsu/node-prebuilt/tarball/master, required by ffi@2.0.0
npm ERR! missing: fibers@https://github.com/icenium/node-fibers/tarball/v1.0.15.1, required by ios-sim-portable@1.7.0
npm ERR! missing: nodobjc@https://github.com/telerik/NodObjC/tarball/v2.0.0.5, required by ios-sim-portable@1.7.0
npm ERR! missing: ffi@https://github.com/icenium/node-ffi/tarball/v2.0.0.5, required by nodobjc@2.0.0
npm ERR! missing: ref@https://github.com/icenium/ref/tarball/v1.3.2.3, required by nodobjc@2.0.0
npm ERR! missing: ref-struct@https://github.com/telerik/ref-struct/tarball/v1.0.2.5, required by nodobjc@2.0.0
npm ERR! missing: prebuilt@https://github.com/tailsu/node-prebuilt/tarball/master, required by ref@1.3.2
npm ERR! missing: ref@https://github.com/icenium/ref/tarball/v1.3.2.3, required by ref-struct@1.0.2
npm ERR! missing: prebuilt@https://github.com/tailsu/node-prebuilt/tarball/master, required by bufferutil@1.0.1
npm ERR! missing: prebuilt@https://github.com/tailsu/node-prebuilt/tarball/master, required by utf-8-validate@1.0.1
`

**Comment by sinedied** [comment]
You definitely have an issue with your node/npm installation, as seen from the errors from your global modules and the versions listed from the project which are not the latest ones.

Do you use a node version manager, like `nvm` or `n`? sometimes things go wrong during node version switching, leading to strange deps issues. If you do, try switching to a newer `node@8` version so the local links gets refreshed.

Then also try again reinstalling your modules after removing your `package-lock.json` file in you project folder:
```
rm -f package-lock.json
rm -rf node_modules/
npm cache clean --force
npm install
```

Then check if installed versions are correct with `npm ls @angular/cli @ngx-rocket/scripts --depth=0`, you should get:
```
├── @angular/cli@6.0.8 
└── @ngx-rocket/scripts@2.2.0 
```

If it's still not good, you might want to try `npm doctor` to see what could be wrong with your environment.

**Comment by adappter** [comment]
How could it be possible that my version of my project are not the latest? I just created the project with your 5.0.1 version.

npm ls @angular/cli @ngx-rocket/scripts --depth=0 gives me the values you mentioned and npm doctor shows me this:

`Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v6.1.0
node -v                             v10.4.1
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 2669 tarballs
`

**Comment by sinedied** [comment]
> How could it be possible that my version of my project are not the latest? I just created the project with your 5.0.1 version.

The versions of the modules installed by npm, as shown by your previous `npm ls --depth=-` were not right (@angular/cli@6.0.7 and @ngx-rocket/scripts@2.1.0 for instance).

Did you change anything in the generated project, like in `index.html` or in your `package.json`? Do you also have the error with `npm run build --base-href ./`?

**Comment by sinedied** [comment]
@adappter did you fix your issue?

**Comment by adappter** [comment]
I will give you a feedback. I don't have access to my mac currently

**Comment by adappter** [comment]
The Problem was the index.html. I changed the base href there because I wanted to upload the PWA on my server. Just reverted it to the default.
