### ISSUE TITLE
question with usage http to request in assets directory

### ISSUE THREAD

**Issue by Paul75** [ngx-rocket/generator-ngx-rocket#337]
Hello,

When I can got access to file where is in assets ? I want to have in assets json file and read the file ?

Thanks

**Comment by sinedied** [comment]
Files in the assets folder are put there to usually be copied as-is on the output folder, like images etc but you need to specify the files you want to copy in `angular.json`.

As for your json files, it depends what you're trying to achieve:
- if you just want to use the json data in your code, you can put it anywhere and import it directly:
```ts
import * as json from './you-file.json';
```
- if you want to load it asynchronously at runtime, put it in the assets folder and add it to the copied resources in `angular.json`, then just perform an http request to load it using`HttpClient`.

**Comment by bursauxa** [comment]
@Paul75 was the above information of any help?
