### ISSUE TITLE
ApiPrefixInterceptor - avoid to change URL if it starts with http/https

### ISSUE THREAD

**Issue by dm-CaT** [ngx-rocket/generator-ngx-rocket#338]
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior
In case of use of third-party packages there is no possibility to disable API prefix for particular request. 
This causes problem when third-party packages tries to access external server using full path URL.

## Expected behavior
ApiPrefixInterceptor should check if url starts with http or https and in case of yes avoid modification

## Environment

```
- generator version: 5.0.1
- node version: 8.11.1  <!-- run `node --version` -->
- npm version: 5.8.0  <!-- run `npm --version` -->
- OS:  Windows 10 <!-- Mac, Linux, Windows -->
```

Others:

I faced this problem when worked with angular-auth-oidc-client package. It requests additional data about authorization using http request to external server. To avoid that propose to modify ApiPrefixInterceptor something like this

```
@Injectable()
export class ApiPrefixInterceptor implements HttpInterceptor {
  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (!/^(http|https):\/\//i.test(request.url)) {
      request = request.clone({ url: environment.serverUrl + request.url });
    }
    return next.handle(request);
  }
}
```

**Comment by sinedied** [comment]
Sure, that would be a valid change, you can submit a PR!

Just to nitpick, testing for `http(s):` is enough, no need for the `//`, ie `/^(http|https):/` for the regex 😉

**Comment by dm-CaT** [comment]
I'll do that
