### ISSUE TITLE
Discussion: momentjs support option

### ISSUE THREAD

**Issue by dm-CaT** [ngx-rocket/generator-ngx-rocket#341]
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior
There is no support for [http://momentjs.com/](http://momentjs.com/) for now out of box in generator. 
momentjs can be used in [angular material 2](https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings) and officially supported by AM2 team. 

## Expected behavior
I propose to discuss possibility to include momentjs support option. First of all for http service which retrieves data from backend. For now I have quick solution implemented in the same way like other http interceptors did.
Service to revive strings representing date objects from json.
```
@Injectable()
export class MomentConvertService {
  public convert(data: HttpResponse<any>): any {
    const body = data.body;
    if (body && body !== '') {
      const stringBody = JSON.stringify(body);
      return JSON.parse(stringBody, this.reviver)
    }
    return body;
  }

  private reviver(key: any, value: any): any {
    if (typeof value !== 'string') {
      return value;
    }
    if (value === '0001-01-01T00:00:00') {
      return null;
    }
    const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*)?)/.exec(value);
    if (!match) {
      return value;
    }
    return moment(value);
  }
}
```
Interceptor to handle requests
```
@Injectable()
export class MomentConvertInterceptor implements HttpInterceptor {

  public constructor(private momentConvertService: MomentConvertService) { }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (request.responseType !== 'json') {
      return next.handle(request);
    }

    return next.handle(request).pipe(map(event => {
      if (event instanceof HttpResponse) {
        const body = this.momentConvertService.convert(event);
        return event.clone({ body });
      }
      return event;
    }));
  }
}
```

Modified HttpClient / HttpService
```
export interface HttpClient {
...
disableMomentConvert(): HttpClient;
...
}

export class HttpService extends HttpClient {
...
  disableMomentConvert(): HttpClient {
    return this.removeInterceptor(MomentConvertInterceptor);
  }
...
}
```

In addition to changes in HTTP requests processing we can pre-configure provider declarations and formats in app.module

 ```
 providers: [
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE] },
    { provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS }
```

What do you think about that? 
Will it be useful for implementation inside generator? Or, maybe it has to be implemented as standalone addon?

**Comment by sinedied** [comment]
That would definitely be a good candidate for an addon I think, as it's still an implementation specific feature (never used an approach like this, as we prefer using models to perform the DTO transforms) but could be useful to others.

**Comment by sinedied** [comment]
For a basic addon example, you can take a look at https://github.com/ngx-rocket/addon-example and start from `ngx new --addon`. We are still working on more extensive examples and documentation, that will probably come after the big features currently in the pipe are landed.

As for using models to perform the DTO, I usually rely on generated code from the API swagger spec, using tools like https://github.com/RSuter/NSwag and https://github.com/swagger-api/swagger-codegen. Then you automatically have properly typed models with DTO transforms and correct objects for dates, enums, arrays. The bonus is that you have to maintain a proper a swagger doc on your API to make it work 😉

**Comment by sinedied** [comment]
Closing as this is more fit for a 3rd party addon.
