### ISSUE TITLE
Angular Ionic module lazy load problem

### ISSUE THREAD

**Issue by darron1217** [ngx-rocket/generator-ngx-rocket#342]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

Lazy loading module emits the error `ERROR Error: Uncaught (in promise): invalid views to insert`

## Expected behavior

Successfully lazy load module by using angular router's `loadChildren`

## Minimal reproduction of the problem with instructions

`app.component.ts`
```typescript
  ngOnInit() {
    const onNavigationEnd = this.router.events.pipe(filter(event => event instanceof NavigationEnd));

    // Bind Ionic navigation to Angular router events
    onNavigationEnd.subscribe(() => this.updateNav(this.activatedRoute));
  }

  private updateNav(route: ActivatedRoute) {
    if (route.component === IonicApp) {
      if (!route.firstChild) {
        return;
      }
      route = route.firstChild;
      if (!this.nav.getActive() || this.nav.getActive().component !== route.component) {
        this.nav.setRoot(route.component, route.params, { animate: true, direction: 'forward' });
      }
    }
  }
```

`app-routing.module.ts`
```typescript
const routes: Routes = [
  // Fallback when no prior route is matched
  { path: '', redirectTo: 'projects', pathMatch: 'full' },
  { path: 'projects', loadChildren: 'app/project/project.module#ProjectModule' },
];
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
  providers: []
})
export class AppRoutingModule { }
```

`project-routing.module.ts`
```typescript
const routes: Routes = [
  { path: '', component: ProjectComponent },
];
@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: []
})
export class ProjectRoutingModule { }
```

then, emits error
```
ERROR Error: Uncaught (in promise): invalid views to insert
    at resolvePromise (zone.js:809)
    at Object.eval [as reject] (zone.js:728)
    at NavControllerBase._fireError (nav-controller-base.js:223)
    at NavControllerBase._failed (nav-controller-base.js:216)
    at eval (nav-controller-base.js:263)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4749)
    at ZoneDelegate.invoke (zone.js:387)
    at Zone.run (zone.js:138)
    at eval (zone.js:858)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
```
## Environment

```
- generator version: X.Y.Z
- node version: `v8.11.3`
- npm version: `5.6.0`
- OS:  `Window10`
```

Others:

**Comment by sinedied** [comment]
Lazy loading cannot be used with Ionic due to specificities of their navigation system, hence it's not proposed as a generator option.

**Comment by sinedied** [comment]
What do you mean by "overload shared service with custom one"?

`shared` module should not have services in it and also not a `forRoot()` import method, that's the role of the `core` module, but then keep in mind that services put in it are **singleton** (see https://stackoverflow.com/questions/42695931/angular2-coremodule-vs-sharedmodule top answer).

If you only want to share methods of a service but add some others specific to your feature modules, you can always extend your shared service into a new service class with only added methods in each of your feature modules.

**Comment by darron1217** [comment]
Oh yes...
I studied more and found the solution
Thanks for your help :)
