### ISSUE TITLE
Add Admin module Feature

### ISSUE THREAD

**Issue by zeusmos** [ngx-rocket/generator-ngx-rocket#345]
any plans to include admin module with role guard, the core functionality of admin are parent/child crud operation.

**Comment by bursauxa** [comment]
Hello @zeusmos, could you expand on what you mean with "admin module" ? Is it something like [this](https://ryanchenkie.com/angular-authentication-using-route-guards) ?

**Comment by zeusmos** [comment]
yes, the main AppRoutingModule should have AuthGuard to LoadChildren AdminRoutingModule and the AdminModule will have it’s own routing module - AdminRoutingModule and the routes to its admin only child components eg:-(dashboard, user management etc... should have few CRUD functionality)

**Comment by bursauxa** [comment]
@zeusmos I am unsure as to what you want to accomplish here. To me it looks like you only need to use the requested route in the `canActivate` function and respond accordingly. You can have a look at the docs : https://angular.io/api/router/CanActivate

Also, route guards only affect the client side of the application, they are completely unrelated to CRUD functionality. CRUD APIs should be protected server-side.

**Comment by zeusmos** [comment]
i know that is correct, but i was looking if you can add few templates e.g. if an user with admin role logs in a new menu item should show and has access to admin screens and a regular user will be restricted to access these screen. also with few templates for admin role like form entry screen and a datatable screen has master/detail page having datasource from a mock data or from a firebase database api.

**Comment by sinedied** [comment]
Oops, missed that one sorry! 😞 
I stand with @bursauxa on this one, it might be too context-specific in both how to present and to implement it, like using RBAC or something else.
This might be a good addition to the doc, though I would definitely approve a PR for that 😉
