### ISSUE TITLE
Replace HTMLHint by htmllint

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#347]
Since HTMLHint is pretty much [dead by now](https://github.com/yaniswang/HTMLHint/issues/214#issuecomment-409269132), I propose to replace it by a new emerging tool that seems promising, [Markuplint](https://github.com/markuplint/markuplint)

EDIT: It seems that some people reported that Markuplint is not quite ready for prime time 😞 Has issues with angular template, among others... Let's see how this evolves, maybe another suitable replacement can be found.

Here is another candidate: https://github.com/htmllint/htmllint-cli

**Comment by sinedied** [comment]
https://github.com/thedaviddias/HTMLHint is ALIVE 🎉 
The project has been transferred to volunteers which have updated the project, merged the PR and fixed the security issues 👏 

So the question to replace it is now only a matter of "can we find a better tool"?

**Comment by bursauxa** [comment]
Good news from the HTMLHint front 👏 

In the current state of things I believe we should stick to HTMLHint. I see no strong incentive to switch to another tool now that the security vulnerabilities are fixed (although of course other suggestions are welcome).

We should probably kill the associated PR (#355 ) too.
