### ISSUE TITLE
How change default routing

### ISSUE THREAD

**Issue by sdediya** [ngx-rocket/generator-ngx-rocket#349]
Hi,
I need to change default routing /home to /about. 
How can I do please suggest me?
I tried with changing { path: '', redirectTo: '/about', pathMatch: 'full' } in about-routing.module.ts but it's not working in my condition

**Comment by bursauxa** [comment]
You should add the redirection in `about-routing.module.ts` as you did, but also remove the redirection in `home-routing.module.ts`, otherwise they will collide.

Also you said you *changed* the route, but the redirection should be *added* to the original route, it is not a replacement.

**Comment by bursauxa** [comment]
@sdediya, was the above information of any help?

**Comment by bursauxa** [comment]
Closing this as the question was answered.
