### ISSUE TITLE
Cannot run cordova build 

### ISSUE THREAD

**Issue by Madnestranger** [ngx-rocket/generator-ngx-rocket#363]
Hi. 
I'm trying to run build on mobile based project (with Cordova and Ionic) which was build with generator-ngx-rocket.
When I run 
`npm run cordova:prepare`
I always get an error 
`npm ERR! missing script: cordova:prepare`
Cordova is installed globally.
What else I must unstall to make this work?
Thank you.

**Comment by sinedied** [comment]
Can you post your `package.json` files?

This error indicates that the `cordova:prepare` script is not present in it, which is not normal.
Beside, you don't need any additional install to make it work (global cordova is not needed, a local one to the project is installed and used).

And please follow the issue template as it's hard to help if we don't know  which version/params you used on which system, etc.

**Comment by sirockin** [comment]
I searched through this repo and found the following scripts which I have now pasted in manaully:
```
    "cordova:prepare": "ngx-scripts cordova prepare",
    "cordova:run": "ngx-scripts cordova run",
    "cordova:build": "ngx-scripts cordova build --device --release --copy dist",
    "cordova:clean": "ngx-scripts clean",
    "cordova": "cordova"
```
Perhaps there is a bug in the generator which is not inserting these when the cordova options is generated (I'm in Windows so perhaps the CLI selector doesn't work so well in there)

**Comment by bursauxa** [comment]
Closing due to not receiving feedback from the author.
