### ISSUE TITLE
Where to configure the routing guard?

### ISSUE THREAD

**Issue by leihg** [ngx-rocket/generator-ngx-rocket#370]
Where to configure the routing guard?

**Comment by bursauxa** [comment]
It depends on what exactly you want to configure, but for a start you could have a look at the AuthenticationGuard class itself:  https://github.com/ngx-rocket/starter-kit/blob/master/src/app/core/authentication/authentication.guard.ts

**Comment by leihg** [comment]
Can we get the routing URL before routing the route we want to jump?


On 9/4/2018 15:43，Antoine Bursaux<notifications@github.com> wrote：

It depends on what exactly you want to configure, but for a start you could have a look at the AuthenticationGuard class itself: https://github.com/ngx-rocket/starter-kit/blob/master/src/app/core/authentication/authentication.guard.ts

**Comment by bursauxa** [comment]
Absolutely, our default `AuthenticationGuard` is very basic, but you can notice it implements the `CanActivate` class provided by Angular, and the `canActivate` function does receive the route as a parameter :

https://angular.io/api/router/CanActivate

**Comment by leihg** [comment]
Description: In my project, there is a sub-module, but because of permission issues, only five sub-menu modules can be displayed, but in the browser's address bar input other module routing can also be accessed, which should not be allowed, I actually use the route guard to achieve, but in the jump routing Before, I want to get the route to be entered so that I can use it to achieve permission.
On 9/4/2018 15:52，Antoine Bursaux<notifications@github.com> wrote：

Absolutely, our default AuthenticationGuard is very basic, but you can notice it implements the CanActivate class provided by Angular, and the canActivate function does receive the route as a parameter :

https://angular.io/api/router/CanActivate

**Comment by bursauxa** [comment]
Yes, this is exactly what you can achieve with the `canActivate` function. It automatically receives the route as first parameter.

**Comment by bursauxa** [comment]
Closing this as the question was answered.
