### ISSUE TITLE
UI breaking in Production build

### ISSUE THREAD

**Issue by dhavalsoni2001** [ngx-rocket/generator-ngx-rocket#371]
## I'm submitting a...

- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

When I am running production build by executing the command **npm run build**  production build UI is breaking.

## Expected behavior

Project UI should be the same as the development build in the production build.

## Environment

```
- generator version: 5.0.1
- node version: 10.9.0  <!-- run `node --version` -->
- npm version: 6.2.0  <!-- run `npm --version` -->
- OS: Mac
```

Others:
I am running a production build using **http-server** package.

**Comment by sinedied** [comment]
can you post the content of your `.yo-rc.json` file and the result of `ngx ng --version` ?

I discovered an issue with latest Angular CLI version and production builds with Ionic 3, might be related :/

**Comment by dhavalsoni2001** [comment]
**.yo-rc.json**

`{
  "generator-ngx-rocket": {
    "version": "5.0.1",
    "props": {
      "location": "path",
      "appName": "appName",
      "target": [
        "web"
      ],
      "pwa": false,
      "ui": "material",
      "layout": "simple",
      "auth": false,
      "lazy": false,
      "angulartics": false,
      "projectName": "leaflet-map",
      "packageManager": "npm",
      "mobile": []
    }
  }
}`
 and attached ngx ng --version

![screen shot 2018-09-06 at 8 15 14 pm](https://user-images.githubusercontent.com/11704436/45165284-27b30800-b212-11e8-9afe-640bc8b23473.png)

**Comment by sinedied** [comment]
Thanks! Can you also post the error message you have during your production build?

It's often related to AOT, so seeing the message can help.

**Comment by dhavalsoni2001** [comment]
@sinedied I am not getting any error. It runs successfully.

> app-name@1.0.0 build /Users/dhavalsoni/app-name
> npm run env -s && ng build --prod

                                                                                        
Date: 2018-09-07T09:11:12.615Z
Hash: b8c5a91097f34b479bd9
Time: 58035ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.859b5130a820599b6972.css (styles) 57.7 kB [initial] [rendered]
chunk {2} polyfills.250ef2a4b02c50c382fe.js (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.33dd3882d1f77e21013f.js (main) 1.22 MB [initial] [rendered]

**Comment by sinedied** [comment]
So what's the issue actually, is it a visual issue? In that case could you post screenshot of dev/prod build that shows the difference?

If it's a runtime error, can you post the error and stacktrace shown in the dev console?

**Comment by dhavalsoni2001** [comment]
@sinedied Please check below screenshot: 
**Dev:**
![local1](https://user-images.githubusercontent.com/11704436/45212059-8d0a0600-b2b1-11e8-81f5-8915d429aab6.png)
![screen shot 2018-09-07 at 3 19 33 pm](https://user-images.githubusercontent.com/11704436/45212101-ab700180-b2b1-11e8-8495-9f866f5063c2.png)

**Prod:**

![prod1](https://user-images.githubusercontent.com/11704436/45212075-9bf0b880-b2b1-11e8-8198-702ccade13e2.png)
![prod2](https://user-images.githubusercontent.com/11704436/45212094-a57a2080-b2b1-11e8-991a-9ff30d32756e.png)

**Comment by sinedied** [comment]
Seems related to the `preserveWhiteSpaces` option of the angular compiler, you might try changing the value in `src/tsconfig.app.json` to:
```
  "angularCompilerOptions": {
    "preserveWhitespaces": true
  }
```

This option should behave the same in dev & prod, but these days the Angular CLI is full of bugs 😞

**Comment by dhavalsoni2001** [comment]
@sinedied It's already true : 
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts",
    "**/*.mock.ts"
  ],
  "angularCompilerOptions": {
    "preserveWhitespaces": true
  }
}

```

**Comment by dhavalsoni2001** [comment]
@sinedied  Yes it's working pretty good and some of the UI issue fixed, however, there were still some CSS issues and I overwrite it.

**Comment by bursauxa** [comment]
@dhavalsoni2001 I'm assuming we can close the issue then?

**Comment by dhavalsoni2001** [comment]
@bursauxa Yes. As @sinedied  mentioned that it's angular-CLI issue.
