### ISSUE TITLE
Add optional libraries / tools choice

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#381]
As discussed in https://github.com/ngx-rocket/generator-ngx-rocket/pull/356, we should removed extra libraries (only lodash ATM) from the current templates, but propose a choice to integrate popular libraries directly if needed.

And after working on prettier integration, I found https://compodoc.app today and was thinking that the same logic could be applied to optional tools.

For optional libs, I had in mind:
- Lodash: https://lodash.com/
- Moment: https://momentjs.com/docs/
- Date-fns: https://github.com/date-fns/date-fns (a modern moment alternative, supporting tree shaking)
- Ramda: https://github.com/ramda/ramda (a faster, smaller, functional alternative to lodash)

As for optional tools:
- Hads: local wiki system, https://github.com/sinedied/hads (currently built-in)
- Compodoc: Angular doc generator (https://compodoc.app)
- Prettier: code formatter, https://prettier.io (soon built-in as an option)
- Cucumber: natural language test driven framework (https://github.com/protractor-cucumber-framework/protractor-cucumber-framework)

Other optional tools that would need more in-depth modification (will create separate issue for these):
- Jest in place of Karma/Jasmine for UT (see https://github.com/meltedspark/angular-builders/tree/master/packages/jest)
- Testcafe in place of Protractor for e2e tests (https://github.com/DevExpress/testcafe)
- Cypress in place of Protractor for e2e tests (https://www.cypress.io)

What do you think?
Anything else you would see fit in one of those lists?

**Comment by bursauxa** [comment]
Good idea, I wanted to do it for Lodash and Moment already but could not find the time. I have no opinion regarding the others as I have no experience with them.

**Comment by captaincaius** [comment]
As for optional tools, do you folks have any interest in cucumber?  I use protractor-cucumber-framework and it would probably be a pretty simple addition.

**Comment by sinedied** [comment]
As for cucumber, I'm not personally found of it but I know a few folks who use it.
I'll add it to the list, if you're willing to do a PR for it after the initial work on this issue has been done 😉

**Comment by captaincaius** [comment]
:D ok.  ya lots of people dislike it, so I thought I should ask first.  It's easy enough to add after generating, so I didn't want to clutter the project if I'm the only one benefiting from it :P.

**Comment by AdaskoTheBeAsT** [comment]
Do you also have in plans  adding some additional choices 
like "jest" as a replacement for "karma-jasmine" combo and
"testcafe" instead of protractor ?

**Comment by sinedied** [comment]
@AdaskoTheBeAsT That could be a good idea, but it's not quite a just a "drop-in" addition like the others, as it needs more in-depth modification of the project and sources. I'll add that for reference, but will probably create a separate issue for this as it needs a fair amount of work. Besides testcafe, Cypress is also a popular e2e testing option.

**Comment by captaincaius** [comment]
another possibly controversial one: ng-tailwindcss ?

**Comment by sinedied** [comment]
@captaincaius This one would be more an additional UI library choice along Material, Bootstrap and Ionic no? I'm all for it, but this should be a separate issue as it needs new templates, not a minimal plug-in change in package.json 😉
