### ISSUE TITLE
Infinite loop when moving `AppRoutingModule` before `LoginModule ` in `imports` in `AppModule`

### ISSUE THREAD

**Issue by skorunka** [ngx-rocket/generator-ngx-rocket#384]
## I'm submitting a...
- [x ] Bug report

## Current behavior
When moving `AppRoutingModule` before `LoginModule` in `AppModule` `imports`, like:

```
    AppRoutingModule,
    LoginModule,
  ],
```

The app gets into infinite loops with outputs to console:
`'Not authenticated, redirecting...'`

## Expected behavior
App should woke regardless of position of imported modules.

## Minimal reproduction of the problem with instructions
1. `ngx new`
2. Edit the `app.module.ts`, move `AppRoutingModule` before `LoginModule` in `imports`.
3. `npm start`
4. open `localhost:2000` in the browser

## Environment

```
- generator version: 5.1.0
- node version: 10.9.0
- npm version: 6.4.1
- OS:  Windows
```

**Comment by sinedied** [comment]
That's expected, as the import order of the routing modules affects the route declarations, as specified by the Angular framework.

`AppRoutingModule` should always be the last routing module to be imported as it contains the fallback route `{ path: '**', redirectTo: '', pathMatch: 'full' }`.

I fail to see what we could fix regarding this?

**Comment by skorunka** [comment]
Wow, didn't really know that order matters. Its' a bit smelly, isn't it?
Anyways, I think having a comment next to `AppRoutingModule` like `// Must be last imported module` would help.

**Comment by bursauxa** [comment]
I do not see why that would be smelly. What criteria, other than declaration order, would you use to elect only one route in cases where there are conflicting path patterns ?

And by definition, `*` conflicts with every other path pattern.

**Comment by skorunka** [comment]
Smelly is, that the order of imports can break your code. It just smells to me as a developer. But that's not the purpose of this discussion.

**Comment by skorunka** [comment]
@sinedied Ok, that makes sense. I will create PR tomorrow.
