### ISSUE TITLE
Explicitly document the licence for the generated code

### ISSUE THREAD

**Issue by r3mi** [ngx-rocket/generator-ngx-rocket#385]
## I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

## Current behavior
The licence for the generated code is not explicitly stated.
As there is no strong distinction between the templates from the generators (`generator-ngx-rocket` or `angular-cli`) and the generated files, we can _assume_ that the generated code is MIT (same licence as both generators). But it would be better to be explicit, in particular for enterprise users. 

## Expected behavior
Add an explicit statement in the generator's documentation. 
And/or in the generated code ? (in individual files ?, not for the whole generated project, which the user might choose to licence under a different licence) 

Great project. Many thanks @sinedied and contributors !

**Comment by bursauxa** [comment]
I feel like granting such a license would mean that we can 100% guarantee that the entire build chain (angular-cli, webpack, sass, typescript minify, etc etc) does grant you an equivalent license. I mean, if we said "go ahead use our code" but the webpack license itself said "you are free to use webpack but you are forbidden from distributing its output", our statement would probably infringe on Webpack's rights, and in turn they could sue us if you distributed code built by webpack through the ngx-rocket scripts. Probably. I am not a lawyer 🤷

**Comment by sinedied** [comment]
I'm not sure it would be wise to put the generated code under any kind of license. The generator itself and its templates are under MIT, if you clone the starter kit repo it's the same, that's one thing.

But as long as you generate code, I assume it's yours and you can license it however you want. I don't know any similar code generator that impose such a license on generated code, if you find one I'm interested  😃 

Even [angular-cli](https://github.com/angular/angular-cli), [create-react-app](https://github.com/facebook/create-react-app?files=1) or [vue-cli](https://github.com/vuejs/vue-cli) do not restrict their generated code under any license AFAIK, and I don't think it would make sense anyways (whose the copyright holder in that case, the generator itself? 🤔)

Like @bursauxa I'm no lawyer, but from my point of view, excluding the toolchain on which each tool has its own license, the generated app code is completely yours to license under any terms you may see fit.

**Comment by r3mi** [comment]
thanks for the reply. 

For the translating tools (minifiers, css compilers, transpilers, packing tools, ...)  I don't think there is much worries about the output, which traditionally falls under the same licence as the input source code (think : compilers) 

My issue is mainly about code generated by the generators from the templates i.e. the sources created after the initial generation.  Maybe at the minimum to clarify the licence for the code generated from your `generator-ngx-rocket` templates ? (and maybe similar issues should be raised for upstream generators, `angular-cli`, ... ?)

**Comment by bursauxa** [comment]
The Angular guys have not answered this issue in nine months. Closing this as I do no think we could do better than them.
