### ISSUE TITLE
Prepare 6.0 release

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#387]
This is an open ticket to prepare the `6.0` release, that will currently include these major changes:
- Electron support
- Ionic 4 support (and removed Ionic 3 support)

Until finalized, the `6.0` release will be developed under the `release/6.0.x` branch and deployed on npm using a `-beta` suffix and on the `@next` tag.

These are the tasks remaining to finalize this release, feel free to edit/update:
- [x] Add desktop platform choice for Electron
- [x] Ionic 4: replace the hard-to-follow async/loading stuff following @luiza-cicone PR comment (link to it?)
- [x] Update the ionic coding guide, as issues described in it are no more relevant
- [x] Wait for Ionic 4 to iron out its issues (wait for final version?)
- [ ] unpin-ionic-dependencies - remove its residue entirely
- [x] after ionic's theming has settled, make sure the ionic version is just as pretty as the ionic 3 version was
- [x] after ionic's router has settled enough, make sure we're still using it properly (i.e. ensure the nav stack isn't sneaking its way in)
- [x] Bump Angulartics to v7

**Comment by gvishwanath** [comment]
Is possible integrate with socket.io or primus implementation for live reload.

**Comment by sinedied** [comment]
@gvishwanath This issue is not the place to request features, its goal is just to list remaining work regarding already developed issue.

**Comment by captaincaius** [comment]
Here's a few ionic-specific things I think maybe we should add to the list:

- unpin-ionic-dependencies - remove its residue entirely
- after ionic's theming has settled, make sure the ionic version is just as pretty as the ionic 3 version was
- after ionic's router has settled enough, make sure we're still using it properly (i.e. ensure the nav stack isn't sneaking its way in)

**Comment by captaincaius** [comment]
Ah, almost forgot...  They don't have RTL support finished yet.  I don't know much about RTL, but there are some outstanding issues, and every few days I see some discussion in slack about it.

**Comment by sinedied** [comment]
@captaincaius I added your suggestions to the list.

About RTL, I don't think we ever specifically cared for it (shame on us!) so I don't think it's a blocking issue, still it's good to know if someone asks 😄
It may be worth creating an issue to check if our other templates (material, bootstrap) works properly with RTL too.

**Comment by captaincaius** [comment]
might be a good time to (try to) update ionic again :) the beta release notes said they overhauled theming and tabs
hopefully it's actually testable ;)

**Comment by sinedied** [comment]
@captaincaius I updated Ionic along Angular in this branch/PR: https://github.com/ngx-rocket/generator-ngx-rocket/pull/403
But it needs some update for the Ionic tabs code, and some UT fails with the latest Ionic update :/
Feel free to take a look and update the branch

**Comment by captaincaius** [comment]
ah awesome!  i'll try to take a crack at it this weekend :)

**Comment by captaincaius** [comment]
Friends...  ionic 4 is at RC 0 and there's been a grip of breaking changes since beta 16.  If nobody minds I'll try to deal with it today and PR an upgrade.

I'll also see if it's feasible to knock out some of the ionic-related tasks above.

**Comment by captaincaius** [comment]
hmm... do we still need rxjs-compat at this point?

**Comment by sinedied** [comment]
Good call! If I remember well it was kept because of Ionic v3, so we can phase it out I think!

**Comment by captaincaius** [comment]
I think angulartics2 to 7.x should be added to the list here b/c of the angular version dependency.

**Comment by sinedied** [comment]
Good point regarding angulartics, I've bumped the deps the chore/cosmetics PR but have yet to finish working on it. I added it to the checklist.

**Comment by captaincaius** [comment]
ionic-webview security update ... https://ionic.zendesk.com/hc/en-us/articles/360015176994-2019-01-03-Security-Alert-for-cordova-plugin-ionic-webview

do we want to support ios 10?

**Comment by sinedied** [comment]
I'm on the update, and I'll set the minimum target to iOS 11 now, thanks for the reminder 👍 

Now that Ionic 4 final is out, I'm ironing out all the quirks and fixing the CSS, a (big) PR should be up soon 🎉

**Comment by captaincaius** [comment]
Cool! :)

FYI I personally had some troubles trying to update to the 3.x webview... to be honest I can't remember what it was but just a heads up.

**Comment by sinedied** [comment]
@captaincaius If I remember well the point about async/await has been fixed, right?

**Comment by sinedied** [comment]
One final commit to update all dependencies, and we should be good for 6.0 release, unless someone see a blocker?
