### ISSUE TITLE
Cannot detect pageYOffset

### ISSUE THREAD

**Issue by ahmadarif** [ngx-rocket/generator-ngx-rocket#389]
I want to scroll to top after route changed, but the pageYOffset still 0 so my page not scrolling to top.
How to fix it?

**Comment by bursauxa** [comment]
This is not related to the starter kit, it is merely an Angular question.
An efficient answer is available here:
https://stackoverflow.com/questions/39601026/angular-2-scroll-to-top-on-route-change

**Comment by bursauxa** [comment]
I'll point out the important part: from 6.1 onwards, you only need to set the following router option:
`RouterModule.forRoot(routes, {scrollPositionRestoration: 'enabled'})`

As explaiend on [the angular blog](https://blog.angular.io/angular-v6-1-now-available-typescript-2-9-scroll-positioning-and-more-9f1c03007bb6), this will probably become the default option in angular 7.

**Comment by ahmadarif** [comment]
I use this lib https://github.com/nicky-lenaers/ngx-scroll-to but not working, I think this issue because of height in theme.scss using 100%.
If i set the height value using 1000px (example), the scroll function is working.

**Comment by bursauxa** [comment]
As explained in the above comment, you should not be using any lib ; instead, you should use the option directly provided by the Angular router.

**Comment by ahmadarif** [comment]
Same as using lib, maybe this happend when using css config height: 100%.
Case closed, I will change the style.

Thank you :)

**Comment by bursauxa** [comment]
You're welcome ; if there is an issue with a specific style when using the Angular router option, then you should probably log an issue on their github.
