### ISSUE TITLE
npm start does work when app is started, but error comes as "ENOENT: no such file or directory, stat 'D:\projects\ang6\src\app\shared\loader\loader.component.ngfactory.js'" when we modify and save the any file.

### ISSUE THREAD

**Issue by muthukumaroptisol** [ngx-rocket/generator-ngx-rocket#395]
## I'm submitting a...

- [X ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

npm start does work when app is started, but when ever I try to modify and save, compiler fails to reload and below error as shows.
Error: ENOENT: no such file or directory, stat 'D:\projects\ang6\src\app\shared\loader\loader.component.ngfactory.js'
    at Object.fs.statSync (fs.js:948:11)

## Expected behavior

It should be reload without error.

## Environment

```
![error-1](https://user-images.githubusercontent.com/6176436/47036929-37235a80-d19b-11e8-8a65-5119c041fa19.jpg)
![error-1](https://user-images.githubusercontent.com/6176436/47036968-54582900-d19b-11e8-8ca1-b6360d75b3c1.jpg)
- node version: 8.9.1  <!-- run `node --version` -->
- npm version: 5.5.1 <!-- run `npm --version` -->
- OS:  Windows 10<!-- Mac, Linux, Windows -->
```

Others:

**Comment by austinlarue** [comment]
@muthukumaroptisol I'm also receiving this error. What did you end up doing that resolved the issue?

**Comment by muthukumaroptisol** [comment]
@austinlarue I removed --aot in package.json. I saw that problem is for Angular cli version.
