### ISSUE TITLE
E2e tests Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by laura-chesches** [ngx-rocket/generator-ngx-rocket#404]
Hi

I'm submitting a...
- [x] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

I am trying to run the tests from a company that has a proxy. 
I used
call npm config set proxy http://.......:8080
call npm config set https-proxy http://.......:8080
set HTTP_PROXY=http://.....:8080
set HTTPS_PROXY=http://....:8080

But I keep getting this error:
Error: connect ECONNREFUSED ........
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

I also added the proxy in the environment files, but no luck. 

Can you please help?

**Comment by sinedied** [comment]
Does you proxy need auth? If so, did you include it in you proxy config, ie `http://USER:PASS@PROXY_URL:8080` ?

**Comment by bursauxa** [comment]
I have been receiving similar feedback from users behind an uncooperative proxy, I will ask them the same question as you did.

**Comment by sinedied** [comment]
@laura-chesches did you finally found a way to solve this? I'm closing this issue since it's been quite a while, but feel free to reopen it the issue is still there.
