### ISSUE TITLE
HTTP POST does not know the answer to return null returns I want the service to wait for the response

### ISSUE THREAD

**Issue by Erbakar** [ngx-rocket/generator-ngx-rocket#407]
login(context: LoginContext):  Observable<Credentials>  {
    this.http.post<any>(environment.serverUrl + `/login`, context).subscribe(res => {
      this.data = {
        authToken: res.authToken,
        userId: res.userId,
        email: res.email,
        name: res.name
      };
    });
    this.setCredentials(this.data, context.remember);
    return of(this.data);
  }

**Comment by sinedied** [comment]
You have to remove the `subscribe` here, and replace it with `.pipe(.map(...))`.

The observable is subscribed in the `login component`.
The basic rule is to never return subscribed observable from services 😉

**Comment by bursauxa** [comment]
@Erbakar was the answer helpful to you?

**Comment by Erbakar** [comment]
@sinedied  thank you :)
