### ISSUE TITLE
Add Nebular theme

### ISSUE THREAD

**Issue by microSoftware** [ngx-rocket/generator-ngx-rocket#413]
## I'm submitting a...

- [ ] Bug report  
- [x ] Feature request
- [ ] Documentation issue or request

Hello, is it possible to add the [nebular](https://github.com/akveo/nebular) css framework?
Or add a choice of not adding any css framework to the project?

Thank you

**Comment by sinedied** [comment]
You can already generate a project without any CSS library using the `--raw` CLI option.

As for Nebular integration, you can integrate it either as a generator addon, or if you're willing to support it through updates you can submit a PR.

**Comment by sinedied** [comment]
Can be done using an addon, but I don't such integration in the main repo, as we would need someone dedicated to maintain the templates.

**Comment by workcontrolgit** [comment]
I tried to integrate ngx-rocket and nebular.   The demo can be found here https://starterkit-ui.azurewebsites.net/ and the github repo here https://github.com/workcontrolgit/ngx-rocket-nebular
