### ISSUE TITLE
Migrate to async/await everywhere

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#429]
The next logical step following https://github.com/ngx-rocket/generator-ngx-rocket/issues/399, we should do this everywhere there's promises now 😄

**Comment by creal73** [comment]
Do we want to use async/await only where there is promises ?

What about observable subscriptions like in "home.component.ts" ?

**Comment by sinedied** [comment]
Only where there is promises, as for observables it's generally more convenient to keep it like that (for composition etc).
