### ISSUE TITLE
Error Circular dependency when adding either HttpClient or HttpService to AuthenticationService

### ISSUE THREAD

**Issue by geekz-reno** [ngx-rocket/generator-ngx-rocket#436]
## I'm submitting a...

[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
Error Circular dependency when adding either **_HttpClient_** or **_HttpService_** to **AuthenticationService**

`src\app\core\http\http.service.ts -> src\app\core\interceptors\error-handler.interceptor.ts -> src\app\core\index.ts -> src\app\core\core.module.ts -> src\app\core\http\http.service.ts`
`src\app\core\index.ts -> src\app\core\core.module.ts -> src\app\core\http\http.service.ts -> src\app\core\interceptors\error-handler.interceptor.ts -> src\app\core\index.ts`
`src\app\core\interceptors\error-handler.interceptor.ts -> src\app\core\index.ts -> src\app\core\core.module.ts -> src\app\core\http\http.service.ts -> src\app\core\interceptors\error-handler.interceptor.ts`

## Expected behavior
Success compile and can call from **_HttpClient_** or **_HttpService_**

## Minimal reproduction of the problem with instructions
- Generate new project `ngx new`
- Add **_HttpClient_** or **_HttpService_** to login function.

![image](https://user-images.githubusercontent.com/2031382/52503151-3bc2c180-2c17-11e9-815f-f4a1e4f63f81.png)

## Environment
- generator version: 5.3.0
- node version: 8.11.3
- npm version: 6.7.0
- OS:  Windows

Others:
Same issue with:
- [#257](https://github.com/ngx-rocket/generator-ngx-rocket/issues/257)
- [#222](https://github.com/ngx-rocket/generator-ngx-rocket/issues/222)

generator work fine if i use Deprecated **_Http_** and i can't use benefit of HttpService like cache.

Thank you for your great work at this generator.

**Comment by creal73** [comment]
Have you tried with `import { HttpClient } from '@angular/common/http';` or direct import of HttpService `import { HttpService } from '../http/http.service';` ?

**Comment by geekz-reno** [comment]
Hi @creal73, yes i already try both base on prev issue. Do i miss something? Coz i just generate new project and want to call my auth beckend.

Thanks

**Comment by sinedied** [comment]
See my answer to the same issue https://github.com/ngx-rocket/generator-ngx-rocket/issues/432

**Comment by geekz-reno** [comment]
Thanks @sinedied, will try this night.

**Comment by geekz-reno** [comment]
@sinedied , @creal73 thanks for your help,

here my solution in case someone needed,

Create another service in my case `MyAuthenticationService`, and add to provider inside `app.module`

`app.module,`

![image](https://user-images.githubusercontent.com/2031382/52529737-f93dd980-2d29-11e9-9b2f-f7e10da01b3d.png)

`my auth service,`

![image](https://user-images.githubusercontent.com/2031382/52529708-74eb5680-2d29-11e9-952e-bd6bc8fe3ce2.png)

and then you can use that service inside `AuthenticationService`

here is my `AuthenticationService`,

![image](https://user-images.githubusercontent.com/2031382/52529726-a2d09b00-2d29-11e9-99a2-fd67cee24892.png)

and be careful to use import from app/core or direct import service because it will make circular dependent.
