### ISSUE TITLE
Warning on build: ionic-angular

### ISSUE THREAD

**Issue by 4F2E4A2E** [ngx-rocket/generator-ngx-rocket#442]
## I'm submitting a...

- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
Current build with ionic delivers this warning:
```bash
npm start

> eval-app@1.0.0 start /home/src/eval-app
> npm run env -s && ng serve --proxy-config proxy.conf.js

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building 3/3 modules 0 active[HPM] Proxy created: /api  ->  https://api.chucknorris.io
[HPM] Proxy rewrite rule created: "^/api" ~> ""
                                                                                          
Date: 2019-03-22T08:16:32.911Z
Hash: 00a801942da449704e2b
Time: 26581ms
chunk {main} main.js, main.js.map (main) 791 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.3 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.54 MB [initial] [rendered]

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js 27:11-36
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js 37:11-36
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js 27:11-36
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js 37:11-36
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
ℹ ｢wdm｣: Compiled with warnings.
```

## Expected behavior
No warnings. 

## Minimal reproduction of the problem with instructions
Generate app with ionic.

## Environment

```
- generator version: 1
- node version: 11.6.0  <!-- run `node --version` -->
- npm version: 6.7.0  <!-- run `npm --version` -->
- OS: Mac, Linux, Windows

**Comment by sinedied** [comment]
This is normal, please see https://github.com/ngx-rocket/starter-kit/blob/cordova/ionic/docs/coding-guides/ionic.md#limitations-with-angular-cli

Note that these warning will no longer be present on the upcoming ngx rocket v6 version, thanks to the migration to Ionic v4 that is now properly integrated with angular-cli.

**Comment by 4F2E4A2E** [comment]
Thanks 🙏 a lot for the info. This is great news! When can we count on it? npx update will take care of the migration? 🙈

**Comment by sinedied** [comment]
The release is not planned yet, but there not much work remaining so it should not be too long, given that I find some time to do it. 
For the update, the ground work will be done if you follow this procedure https://github.com/ngx-rocket/generator-ngx-rocket#updating-generated-projects, but you will still have to follow https://ionicframework.com/docs/building/migration/ to migrate your own page and components to Ionic 4, this can not be automated unfortunately.
