### ISSUE TITLE
Move circle-ci docker image to main repo

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#454]
To simplify updates & broken build fixes when there is CircleCI or Android SDK updates, I would like to move the Docker image from https://github.com/ngx-rocket/circleci-dockerfiles to this repo, in the `.circle-ci/docker` folder.

For this to work, a new automated Docker build also has to be setup on this repo (@Ekhozie, can you share the rights on the ngxrocket docker accout?) and the `config.yml` file needs to be changed to use the new image.

**Comment by Ekhozie** [comment]
Yes send me your docker id, I will add it to the organization

**Comment by sinedied** [comment]
Since CI has moved to Azure pipelines, this issue can be dropped
