### ISSUE TITLE
coding guide for configurations and environments

### ISSUE THREAD

**Issue by captaincaius** [ngx-rocket/generator-ngx-rocket#475]
## I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

Hi friends.

IMO build-specific configuration is something that's not really well documented on the interwebs - what to put where and why, etc.  There's lots of docs on HOW it works in angular, but I don't think there's anything very good with practical information and examples anywhere.  I ended up taking a lot of wrong-turns and overcomplications myself before finding the best way to do things.

Also, the ngx-scripts "env" is super useful for overcoming existing shortcomings and to someone new to ngx-rocket, its awesomeness doesn't become clear until you actually start to use it (I was confused as heck until @sinedied personally explained it to me in an issue).

I had a need to document this myself, and since we don't have it here, I thought I'd put what I had forward as a rough starting point to see if we want something like this in the coding guide section of the docs.

I started it with the goal of writing something short and sweet, but every word I went to write triggered a "yeah, but" in my head, so it started ballooning out of control :smile:.  Now I understand why googling it has failed me :P.

Anyway, because of that, its quality isn't anywhere near that of the existing docs yet, but since it might not be wanted for inclusion anyway, and even if it IS wanted the scope of its content would probably need discussion anyway, I decided to ask before trying to organize the information better.

LMK if we want something like this, and if so, what its scope should be.

**Comment by sinedied** [comment]
Sorry for the response delay as I was jumping between planes and trains these days, but definitely this is the kind of things we ❤️ in this project, we cannot have enough documentation and I agree this subject is not covered enough globally. I took a quick look at your PR, and besides some cosmetics it looked fine to me, well done 👍 

I will take more time to read it through carefully, thanks for this!

**Comment by captaincaius** [comment]
No worries I totally understand :).  I've got a 16 hour flight on Friday I'm dreading.  Hope you had a good trip!

Okay good to know something like this is welcome - looking forward to your review, cause there's definitely a few things I'd like to change after rereading it myself.

**Comment by haakon-io** [comment]
Yes please! :)
