### ISSUE TITLE
How to create an Angular 6 project with latest version of generator-ngx-rocket 

### ISSUE THREAD

**Issue by ayoubkhan558** [ngx-rocket/generator-ngx-rocket#484]
## I'm submitting a...
- [x] Documentation issue or request

## Current behavior
Currently when i try to create a new Angular project with ngx-rokcet it creates an project with Angular 7.

## Expected behavior
But i want to create Angular 6 project with latest ngx-rocket library.

**Comment by bursauxa** [comment]
That scenario is not supported. ngx-rocket only supports one target Angular version at a time (currently 7, but will soon be 8). We could document this further of course, but in fact it is already written in the project's very description, which currently reads:

> Extensible Angular 7+ enterprise-grade project generator

This information is also found in the npm description (in package.json).

If you want an older Angular version you should use an older version of ngx-rocket (I think 5.2.x was the last ngx-rocket version that shipped with Angular 6).

**Comment by ayoubkhan558** [comment]
I solved this problem by remaining versions in Package.json file and then run this command in cmd in the projec directory.
`npm install`
