### ISSUE TITLE
generate bootstrap header dropdown give page more than 100%

### ISSUE THREAD

**Issue by Paul75** [ngx-rocket/generator-ngx-rocket#488]
## I'm submitting a...

- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Minimal reproduction of the problem with instructions
Only cleate new project and bootrap choice and launch it.

When launch and start page in header the right element with dropdown, when I pass cursor into dropdown it open bug take page more than 100% and got scroll horizontally....

thanks

**Comment by sinedied** [comment]
Indeed, ng-bootstrap updated its API and now the dropdown needs an addition `display="dynamic"` property to automatically adapt the position.
It will be fixed in next patch release

**Comment by Paul75** [comment]
Thanks :)

**Comment by Paul75** [comment]
Hello, I see is not updated .... ?

**Comment by sinedied** [comment]
Hi @Paul75, we used another workaround to fix the initial issue as using "dynamic" didn't worked well at the time. Maybe it's time to reconsider?

**Comment by Paul75** [comment]
Hello,

For me display="dynamic" works ....

@sinedied and is what ?
