### ISSUE TITLE
generating electron app breaks l10n

### ISSUE THREAD

**Issue by tracyjordan** [ngx-rocket/generator-ngx-rocket#500]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

When selecting the electron option during `ngx new` the localization is not working out of the box, similar to issue https://github.com/ngx-rocket/generator-ngx-rocket/issues/165. Although the language selector changes the language in localStorage no strings are replaced. The app name is displayed as "APP_NAME". When generating a "Web app" only everything seems to work fine. 

## Expected behavior

Translatable strings should be replaced.

## Minimal reproduction of the problem with instructions

`ngx new` with the options provided below.

## Environment
<pre><code>

ngX-Rocket: 7.0.2       
Node.js: v12.8.0        
Npm: 6.10.3
OS: win32 x64 10.0.18362

Generated project options:
{
  "generator-ngx-rocket": {
    "version": "7.0.2",
    "props": {
      "location": "path",
      "strict": false,
      "skipInstall": false,
      "skipQuickstart": false,
      "initGit": true,
      "appName": "ngx rocket test 3",
      "target": [
        "web",
        "electron"
      ],
      "pwa": false,
      "desktop": [
        "windows"
      ],
      "ui": "bootstrap",
      "auth": false,
      "lazy": false,
      "angulartics": false,
      "tools": [],
      "utility": [],
      "projectName": "ngx-rocket-test-3",
      "packageManager": "npm",
      "mobile": []
    }
  }
}

Angular CLI: 8.1.3
Node: 12.8.0
OS: win32 x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@angular/cli                      8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Comment by tracyjordan** [comment]
#165

**Comment by geyuqiu** [comment]
Is there any progress on it?

**Comment by sinedied** [comment]
Will take a look, but I'm a bit overloaded for now.
If you want to take a look a it we'll gladly accept a PR.

**Comment by sinedied** [comment]
On it, instead of netflix night, tonight will be bugfix night 😄

**Comment by sinedied** [comment]
Of found it, issue was same as #165 💀 
Long story short:
- Electron needs special care to allow es6 module to load (see https://gist.github.com/smotaal/f1e6dbb5c0420bfd585874bd29f11c43 for details) -> Angular 8 different loading cause app to break if nothing is done
- Quick workaround is to disable Angular differential loading by setting TS target to `es5` (😱 )
- When target is set to `es5`, translations imports like `import enUS from 'some.json';` fails silently, and needs to be changed to `import * as enUS from 'some.json';`

I went for the quick fix this time, but it seems I need to add proper es6 module handling for Electron to the (long) list of things that needs to be improved with Electron.
