### ISSUE TITLE
blank page on refresh

### ISSUE THREAD

**Issue by geyuqiu** [ngx-rocket/generator-ngx-rocket#507]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
npm run electron:run
click cmd r
-> blank page

## Expected behavior
should still load index.html

## Minimal reproduction of the problem with instructions
choose electron with angular

## Environment

<pre><code>

</code></pre>

Others:

**Comment by sinedied** [comment]
You need to build the angular app before with `npm run build`.
I know this is not ideal for now, there is some work to do to improve the developer experience with the electron target, see https://github.com/ngx-rocket/generator-ngx-rocket/issues/460 and https://github.com/ngx-rocket/generator-ngx-rocket/issues/418 if you are willing to help.

**Comment by geyuqiu** [comment]
I forgot to mention that Angular files are already built in dist(.electron)
Actually I solved it setting base-href in index.html :)
