### ISSUE TITLE
Ionic 4 cli commands

### ISSUE THREAD

**Issue by raminnoodle** [ngx-rocket/generator-ngx-rocket#510]
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior

Missing Ionic cli commands for Ionic 4.

## Expected behavior

Would be great to be able to use the ionic cli commands with this. I would even pay for this feature to be implemented or for someone to give me a solution. Having to build my project just to run the cordova command to run the app takes so long. With commands like ionic <code>cordova emulate --lc </code> it speeds up development so much with being able to live reload the code and view the console.log within the terminal.

**Comment by sinedied** [comment]
Did you try running `ionic init` on the project folder, then using `ionic cordova emulate --lc`?

Ionic CLI is built on top of Angular CLI, so there might chance that there is nothing (or very little) to do to make an ngx generated project compatible with Ionic CLI.
