### ISSUE TITLE
Support older browsers in the wizard

### ISSUE THREAD

**Issue by Polyterative** [ngx-rocket/generator-ngx-rocket#512]
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior

There is no coverage of this problem

## Expected behavior

I would like a choice for supporting older browsers like IE 9/11 in the wizard, with automatic polyfill inclusion, updated browserlist file state and Angular 8 conditional bundle setup and generation

**Comment by sinedied** [comment]
This could be added to the list of "additional tools" question ("Old browsers support (IE 9+)" option).
Feel free to propose a PR with 👍

**Comment by sinedied** [comment]
With Angular support for all IE browsers (incl. IE11) being dropped, I'm closing this as it's relevant anymore.
