### ISSUE TITLE
Wrong indendation in package.json in GitHub project starter-kit

### ISSUE THREAD

**Issue by NNTin** [ngx-rocket/generator-ngx-rocket#515]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

Indentation is wrong for `scripts` in package.json file.
https://github.com/ngx-rocket/starter-kit/blob/0e6655ad25ad0d6c12623722fc11cf504370e3aa/package.json#L5

## Expected behavior

Left: current, right: expected
![image](https://user-images.githubusercontent.com/18033169/67552697-df9fbf00-f70b-11e9-95eb-6686645d184c.png)

## Minimal reproduction of the problem with instructions

See attached screenshot

## Environment
https://github.com/ngx-rocket/starter-kit

Others:

I'm creating this issue here due to https://github.com/ngx-rocket/starter-kit/issues/7

**Comment by sinedied** [comment]
The issue have been fixed in the generator, the starter kit repo will be updated when the upcoming release is published.
