### ISSUE TITLE
Proxy issue on default app

### ISSUE THREAD

**Issue by dhameergovind** [ngx-rocket/generator-ngx-rocket#516]
## I'm submitting a...

- [ x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
I am getting the following error right out the box. As soon as the app tries to connect to the chuck norris api, I see the following error in the terminal 
`[HPM] Error occurred while trying to proxy request /jokes/random?category=dev from localhost:4200 to https://api.chucknorris.io (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

## Expected behavior
Should not see above error, connecting to the api from localhost should work

## Minimal reproduction of the problem with instructions
Just clone the base app(https://github.com/ngx-rocket/starter-kit.git), build and run

**Comment by sinedied** [comment]
Just tried and I cannot reproduce the issue.
2 possibilities comes to my mind:
- api.chucknorris.io was down when you were trying (it happens, it's a free public API)
- You have network connection issues. Are you behind a corporate proxy? If so, check that your configuration is correct especially the HTTP_PROXY environment variable.
