### ISSUE TITLE
Angular router animations

### ISSUE THREAD

**Issue by JulienMCo** [ngx-rocket/generator-ngx-rocket#518]
## I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

## Current behavior

Hello,

I've tried to implement router animations. But it doesn't work.
Is there any example how to implement it ?
It seems because off the shell and the double router outlet, nothing happens.
Thanks.

**Comment by sinedied** [comment]
Hi, do you have an example repo for this?
Last time I've played with animations, I had no issues but it's hard to help with only this much info.
