### ISSUE TITLE
About cross domain processing?

### ISSUE THREAD

**Issue by leihg** [ngx-rocket/generator-ngx-rocket#519]
Excuse me, how does NGX rocket handle cross domain requests? Thank you!

**Comment by sinedied** [comment]
I'm not sure what you mean exactly? There's nothing special in this regard as it use Angular's built-in http service, but there's nothing in particular to do on the client side to manage cross origin requests, whatever the framework as it's something that needs to be enabled on the server side.
You should take a look at https://enable-cors.org/server.html to see how you can do it with many server platforms.
