### ISSUE TITLE
After multilingual support is set, it is invalid. What's the matter?

### ISSUE THREAD

**Issue by leihg** [ngx-rocket/generator-ngx-rocket#520]
Hello, author! When I use the project generated by NGX rocket (latest version), I add a Chinese supported Josn file, and then add translateservice.settranslation ('zh-CN ', Zh') to the constructor in the i18n.service.ts file class. How does the method not work? Where didn't I notice? Thank you!

**Comment by sinedied** [comment]
Please follow the issue template to fill back your environment and versions, otherwise it's hard to help.

**Comment by sinedied** [comment]
FWIW, Chinese language will be be directly available in upcoming version. Closing in the meanwhile as there was no feedback.
