### ISSUE TITLE
Upgrade to Angular 9 and bump outdated dependency

### ISSUE THREAD

**Issue by gunjankhanwilkar** [ngx-rocket/generator-ngx-rocket#524]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

Currently there are lots of outdated dependencies which requires attention.

## Expected behavior

Upgrade to IVY - Angular V9 with other outdated dependencies (For ex - utilities like until-destroyed which is already upgraded to Angular V9 with IVY support).

## Environment

<pre><code>

</code></pre>

Others:

**Comment by sinedied** [comment]
ng9 upgrade is already planned an WIP. The ng9 branch is under testing, feel free to help with the migration.
