### ISSUE TITLE
need to add multiple roles

### ISSUE THREAD

**Issue by RajasekharKadasani** [ngx-rocket/generator-ngx-rocket#526]
trying to create a app with ngx-rocket:
after login i need to route based on role,
ex:-  
    login as admin i need to show admin-dashboard
    if login as user neeed to show user-dashbord

as if now in shell how to use this tio manage multiple roles differnt start up page,every route i am making as module

**Comment by sinedied** [comment]
Look at LoginComponent, this is where the redirection is done:
```ts
      log.debug(`${credentials.username} successfully logged in`);
      this.router.navigate([ this.route.snapshot.queryParams.redirect || '/'], { replaceUrl: true });
```
Mananing different roles and behavior is something you have to manage yourself, you can use libraries like https://www.npmjs.com/package/ngx-permissions to help you with that.

**Comment by RajasekharKadasani** [comment]
thank you
