### ISSUE TITLE
How to update to Angular 9

### ISSUE THREAD

**Issue by foxMclion** [ngx-rocket/generator-ngx-rocket#533]
## I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

How can I generate or upgrade an Angular 8 app to version 9 with ngx rocket?

**Comment by foxMclion** [comment]
Ok I've followed these steps: https://update.angular.io/#8.0:9.0

```
$ ng update @angular/core@8 @angular/cli@8
$ ng update @angular/core @angular/cli
```

and then installed localization: `ng add @angular/localize`

and the project compiled successfully.

**Comment by bryanrscott** [comment]
What I don't get it that head looks to have the angular updates applied?  That if I am following the commit trail right (https://github.com/ngx-rocket/generator-ngx-rocket/commit/1de992ea013589c275758dec89574b69a99f371e) .   This commit does have quite a few other changes?

So I would be interested in knowing the "How to generate a angular 9 project"

**Comment by sinedied** [comment]
Master branch has already the Angular 9 updates, but it's not released yet as there's some additional changes I would like to include before.

You can use use `npm i -g https://github.com/ngx-rocket/generator-ngx-rocket.git` if you don't want to wait the next release.

**Comment by foxMclion** [comment]
What would the potential issues be if we update the app manually to angular 9 from latest release?

**Comment by sinedied** [comment]
@foxMclion Take a look at https://update.angular.io

**Comment by sinedied** [comment]
8.0.0 released with Angular 9 support 🎉
