### ISSUE TITLE
angular-cli generator is creating a wrong style extension

### ISSUE THREAD

**Issue by Achraf-vermeg** [ngx-rocket/generator-ngx-rocket#544]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

`ng g c foo` is not creating **scss** style extension.

**angular.json**
```
"example": {
    "root": "projects/example",
    "sourceRoot": "projects/example/src",
    "projectType": "library",
    "prefix": "exam",
    "schematics": {
      "@schematics/angular:component": {
        "styleext": "scss"
      }
    },
 ....
}
```

**PS**
`ng config schematics.@schematics/angular:component.styleext scss` didn't fixed the issue

`ng g c foo --style=scss` fixed the issue

## Expected behavior

**foo.component.scss** should be generated by default instead of **foo.component.css** 

## Minimal reproduction of the problem with instructions

`ng g c foo`

## Environment

<pre><code>
ngx-rocket@8.0.0
</code></pre>

Others:

it works fine in version 7

**Comment by sinedied** [comment]
Thanks for reporting, will look at it. 
Seems like they changed the angular.json schema without notice :(

```
"example": {
    "root": "projects/example",
    "sourceRoot": "projects/example/src",
    "projectType": "library",
    "prefix": "exam",
    "schematics": {
      "@schematics/angular:component": {
        "styleext": "scss" // <===== now must be "style": "scss" to work
      }
    },
 ....
}
```
