### ISSUE TITLE
core.js:7376 ERROR Error: Uncaught (in promise): Error: Component ShellComponent is not part of any NgModule or the module has not been imported into your module. Error: Component ShellComponent is not part of any NgModule or the module has not been imported into your module.     at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._createCompiledHostTemplate (compiler.js:27209)

### ISSUE THREAD

**Issue by niraj114** [ngx-rocket/generator-ngx-rocket#550]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Environment

<pre><code>

</code></pre>

Others:

**Comment by niraj114** [comment]
I generated angular code using ngx-rocket. In that I am trying to implement lazy Lading. I am getting issue

**Comment by sinedied** [comment]
Can you please fill up the issue template with your env details? You just have to copy the results of `ngx --debug-infos` so I can see which version of angular etc you are using, as these kind of errors depends of your angular version.
