### ISSUE TITLE
translations:extract didn't work for .ts files

### ISSUE THREAD

**Issue by Achraf-vermeg** [ngx-rocket/generator-ngx-rocket#551]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
`npm run translations:extract`

didn't extract strings between `extract('Hello')` from ts files 

## Expected behavior
Should have string **Hello** in `src\translations\template.json`

## Minimal reproduction of the problem with instructions

Add `extract('Hello')` in any ts file (component, module,...)

`npm run translations:extract`

## Environment

<pre><code>ngx-rocket@8.0.1</code></pre>

**Comment by sinedied** [comment]
It seems that https://github.com/biesbjerg/ngx-translate-extract has changed the way markers work, you now have to import a specific function from their package 😞
