### ISSUE TITLE
fix: issue auth folder when choose no auth features

### ISSUE THREAD

**Issue by fabiomartino** [ngx-rocket/generator-ngx-rocket#553]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

If we create a new project without auth feature the folder auth exist with inside only index.ts

## Expected behavior

When create a new project without auth feature the auth folder will not created

## Minimal reproduction of the problem with instructions

- Create a new project w/o auth
![no-auth_01](https://user-images.githubusercontent.com/7057691/79618409-44abfe80-810a-11ea-851d-637fdd38b5d3.png)
- You will see the src/app/auth/index.ts is created
![no-auth_02](https://user-images.githubusercontent.com/7057691/79618489-7a50e780-810a-11ea-9fd0-e24d0a9c3dd8.png)
- Is also visible in the IDE
![no-auth_03](https://user-images.githubusercontent.com/7057691/79618529-90f73e80-810a-11ea-9e7c-d35dccfdb39f.png)

## Environment
ngx-rocket: 8.0.1
Node: 13.13.0
OS: Debian linux x64

Others:
I will create a PR to fix this issue

**Comment by sinedied** [comment]
Closed by #554 , thanks for the report & fix
