### ISSUE TITLE
Error deprecated request@2.88.0:

### ISSUE THREAD

**Issue by ANDRESFCC** [ngx-rocket/generator-ngx-rocket#556]
PLEASE HELP US PROCESS GITHUB ISSUES FASTER BY PROVIDING THE FOLLOWING INFORMATION.
ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION.

Error on installation 
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by sinedied** [comment]
As indicated, this is not an error but a warning. Such messages are quite frequent in the Node.js ecosystem and are most often harmless, il will disappear once the related package using it will update or change its dependency. It's not directly related to this package, so we can't do much about it.
