### ISSUE TITLE
How to use less as a style sheet language in a project？？

### ISSUE THREAD

**Issue by jocklei** [ngx-rocket/generator-ngx-rocket#565]
For angular projects created with NGX rocket, the default sass language is used as the style sheet. How to configure the created style sheet to be less???

Thank you for your reply!!

**Comment by sinedied** [comment]
This generator is all about integration, especially with UI components that currently all use SCSS. If you would like to mix some existing LESS styles with it, there's nothing special to do, put your LESS files and reference it in your components.

However, if you want to use LESS for your whole project then you should better start from scratch using the Angular CLI.
