### ISSUE TITLE
The "new" command asks the same information twice

### ISSUE THREAD

**Issue by SalmanTariq** [ngx-rocket/generator-ngx-rocket#566]
## I'm submitting a...
- [x] Bug report  
- [ ] Feature request
- [*] Documentation issue or request
- [ ] Question

## Current behavior
<pre><code>ngx new</code></pre> asks the same information twice

## Expected behavior
Should only ask one time

## Minimal reproduction of the problem with instructions
npm install --global generator-ngx-rocket 
ngx new my-app

![Capture](https://user-images.githubusercontent.com/13284494/90936713-33a82c80-e41f-11ea-9b6e-541b3b45c3e4.PNG)

**Comment by sinedied** [comment]
Thanks for the report, seems that a package update changed the behavior. I'm looking at it.
