### ISSUE TITLE
Routing Module question

### ISSUE THREAD

**Issue by buhosiliscodirococo** [ngx-rocket/generator-ngx-rocket#591]
## I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Question

## Minimal reproduction of the problem with instructions
Hi, I'm a newbie to angular.
My question is how do the routes work in ngx-rocket?

I explain:
Following this example [link](https://www.itsolutionstuff.com/post/how-to-create-routing-module-in-angular-11example.html) works all fine, but the module is imported in **app.module.ts**, compared to the native ngx-rocket _about_  that exists inside **app-routing.module.ts**

<img width="934" alt="Captura de pantalla 2021-03-10 a la(s) 20 30 29" src="https://user-images.githubusercontent.com/78824620/110714045-a8875c00-81e1-11eb-9b5e-d33ff4b30350.png">

in other words
How could I pass the admin module from the previous example inside **app-routing.module.ts** (_AppRoutingModule_)? 

and in addition to this very question,
If another route that goes through **app-routing.module.ts** is publicly accessible (example product prices), can it also go through this routing module? 

_EDIT:_
I have replicated this block of code, filled the fields (_X_) and it works perfect .
`{ path: 'XXXXX', loadChildren: () => import('XXXXX').then((m) => m.XXXXXXXX) }`
Leaving it outside the `Shell.childRoutes` is for public access .

I spent days trying to figure it out and solve it right now that I created the question ... 

Anyway, would that be the correct way to do it or is there another method?

I loved ngx-rocket because it takes you down the path of good practice! 

## Environment
ngx-rocket 9.2.0
macOS Mojave
Visual Studio Code 1.54.1

**Comment by sinedied** [comment]
By default, the about module is generated as a lazy loaded module (this can be switched off) hence why it's a bit different than the example you linked.

The way you solved it totally fine, you created a new lazy loaded module this way (better perf for your main bundle) 🙂 

I encourage you to read the [routing basics](https://angular.io/guide/router#defining-a-basic-route) from the Angular docs, then after that read the [lazy loading basics](https://angular.io/guide/lazy-loading-ngmodules#lazy-loading-basics) that explains the differences with regular routes.

Good luck with your learning journey!
