### ISSUE TITLE
Thx for a najs starter-kit ^_^

### ISSUE THREAD

**Issue by polterguy** [ngx-rocket/generator-ngx-rocket#602]
Here's [where I brought it](https://dzone.com/articles/are-you-guys-still-coding) - Watch the video. Created from your template ...

**Comment by sinedied** [comment]
Thanks for the notice and feedback, will have a look 😉

**Comment by polterguy** [comment]
NP, loved your template. Very tidy, neat and concise. I'm not too skilled with Angular myself, so using something like this in my own stuff, makes my job a *lot* easier. I'll give you credits in its main _"Credits"_ section in the next release. But for now, you'll find a link to your amazing starter-kit in the scaffolded results as you generate a frontend ... ^_^

Pssst, if you've got tips and tricks for how to apply even _more_ cool settings during my scaffolding process, I'd appreciate it ...
