### ISSUE TITLE
Add Cypress support for E2E test

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#604]
Would love to see a Cypress option for E2E tests: https://www.cypress.io/

**Comment by fabiomartino** [comment]
Hi
I created a WIP Pull Request https://github.com/ngx-rocket/generator-ngx-rocket/pull/605

What I do so far is:
1) Generate a sample basic project... no auth, no pwa, no e2e (protractor), english language, and only JEST as unit test tool
2) Using cypress schematics on it `ng add @cypress/schematic` [Install Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress))
3) Add 2 basic tests home.ts and about.ts
4) try it ;)

After this I created a new entry option for cypress next to e2e (protractor) in feature prompt section
manually merge the diff and added the conditions for props.cypress
this is the result:
![cypress1](https://user-images.githubusercontent.com/7057691/126850461-aa43b539-900b-4444-8903-be365dad0f89.png)
![cypress2](https://user-images.githubusercontent.com/7057691/126850496-10adc210-0f8c-4527-9069-be8fff10b424.png)
![cypress5](https://user-images.githubusercontent.com/7057691/126850525-86d74e9d-9fe5-4f8c-bf40-aea96353bc0b.png)
![cypress6](https://user-images.githubusercontent.com/7057691/126850528-d8ca06bd-b748-4793-8a9e-935cf0f21c7d.png)

... cypress have a lot of useful tools like [plugin](https://docs.cypress.io/guides/tooling/plugins-guide#Use-Cases), [code coverage](https://docs.cypress.io/guides/tooling/code-coverage) etc... maybe will the better to have into a separate prompt entry

**Comment by sinedied** [comment]
Awesome, I'll have a look thanks!

**Comment by sinedied** [comment]
Released with 10.1 😉
