### ISSUE TITLE
"@fortawesome/fontawesome-free" errors in console with Angular

### ISSUE THREAD

**Issue by Paul75** [ngx-rocket/generator-ngx-rocket#606]
## I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [X] Question

## Current behavior
When start (npm start) and open console I've got errors : 
GET http://localhost:4200/webfonts/fa-solid-900.woff2 net::ERR_ABORTED 404 (Not Found)
GET http://localhost:4200/webfonts/fa-solid-900.woff net::ERR_ABORTED 404 (Not Found)
GET http://localhost:4200/webfonts/fa-solid-900.ttf net::ERR_ABORTED 404 (Not Found)

## Expected behavior
not errors in console

## Minimal reproduction of the problem with instructions
- launch application with npm start
- open console
- seee errors

## Environment

<pre><code>
ngX-Rocket: 10.0.0
Node.js: v14.17.0
Npm: 7.20.1
OS: linux x64 5.4.0-80-generic

</code></pre>

Others:
nothing

Thanks

**Comment by sinedied** [comment]
I could not reproduce this, seems like a botched package install.
If it happens again, could you try `rm -rf node_modules && npm cache clean --force && npm install` ?
