### ISSUE TITLE
Importing fonts

### ISSUE THREAD

**Issue by PeterSeifert** [ngx-rocket/generator-ngx-rocket#83]
When i try to import a font via @font-face i'll get the following error:

Failed to compile.
```

.//css-loader?{"sourceMap":false,"importLoaders":1}!.//postcss-loader?{"ident":"postcss"}!.//sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/main.scss
Module not found: Error: Can't resolve '../assets/fonts/NGT75__W.eot.eot' in 'E:\Web\EKFAdmin\src'
 @ .//css-loader?{"sourceMap":false,"importLoaders":1}!.//postcss-loader?{"ident":"postcss"}!.//sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/main.scss 6:226355-226398 6:226421-226464
 @ ./src/main.scss
 @ multi ./src/main.scss
```

Is there something im missing or is there an other way to import font-files into the project?

**Comment by sinedied** [comment]
Seems related to related path resolution, see https://github.com/angular/angular-cli/issues/5213 for details and possible fix

**Comment by sinedied** [comment]
@PeterSeifert did you resolve your issue?

**Comment by PeterSeifert** [comment]
@sinedied yes, thank you. The solution described in [angular-cli/issues/#5213](https://github.com/angular/angular-cli/issues/5213) worked for me
