### ISSUE TITLE
Type 'Observable<{} | Response>' is not assignable to type 'Observable<Response>'.

### ISSUE THREAD

**Issue by sprucify** [ngx-rocket/generator-ngx-rocket#95]
I get a type mismatch error in http.service.ts:121 
I'm not sure yet how to fix this.

**Comment by sinedied** [comment]
Do you have this error right after generating a new project, or after some modifications?
If you added modifications, can you post some code?

**Comment by sprucify** [comment]
It works perfect out of the box.
But upgrading to typescript 2.4.* will break it.
I think the error is valid and pop up just because typescript is more strict in the later versions?

**Comment by sinedied** [comment]
Yes you are right, this will be fixed when we release a new version compatible with TS 2.4.

It seems that this new TS version have broken a lot of projects 😄 
That's one of the reasons it's always safer to only allow bugfix updates on such crucial dependencies 😉

**Comment by sprucify** [comment]
I think is has to do with the following changes in Typescript 2.4: Stricter variance in callback parameters

**Comment by sinedied** [comment]
Is this issue still present for your with `TypeScript@2.4.2`? I cannot reproduce it anymore.

**Comment by sagarb3** [comment]
Any fix on this bug ?

**Comment by sinedied** [comment]
This was fixed a while ago when we added `typeScript@2.4.2` compatibility.
